package xeadModeler;

/*
 * Copyright (c) 2012 WATANABE kozo <qyf05466@nifty.com>,
 * All rights reserved.
 *
 * This file is part of XEAD Modeler.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the XEAD Project nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

public class Res extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][]{
		{ "DialogAddList01", "Import CSV" },
		{ "DialogAddList02", "Cancel" },
		{ "DialogAddList03", "Add Subject Areas" },
		{ "DialogAddList04", "Name of Subject Area" },
		{ "DialogAddList05", "Add Roles" },
		{ "DialogAddList06", "Name of Role" },
		{ "DialogAddList07", "Add Tasks" },
		{ "DialogAddList08", "Name of Task" },
		{ "DialogAddList09", "Add Subsystems" },
		{ "DialogAddList10", "Name of Subsystem" },
		{ "DialogAddList11", "Add Subsystem Tables" },
		{ "DialogAddList12", "Name of Table" },
		{ "DialogAddList13", "Add Table Fields" },
		{ "DialogAddList14", "Name of Field" },
		{ "DialogAddList15", "Add Subsystem Functions" },
		{ "DialogAddList16", "Name of Function" },
		{ "DialogAddRelationshipOnDatamodel1", "Adding Table-Relationship" },
		{ "DialogAddRelationshipOnDatamodel2", "Select option to add table-relationship to the target table. Key fields can be added or existing fields can be reused as Foreign-Key. Value of name and ID of fields to be added should be separated by semicolon(;)." },
		{ "DialogAddRelationshipOnDatamodel3", "Paste fields to the target table as foreign key." },
		{ "DialogAddRelationshipOnDatamodel4", "Reuse existing fields to setup relationship." },
		{ "DialogAddRelationshipOnDatamodel5", "New field name" },
		{ "DialogAddRelationshipOnDatamodel6", "New ID(alias)" },
		{ "DialogAddRelationshipOnDatamodel7", "Cancel" },
		{ "DialogAddRelationshipOnDatamodel8", "Number of name and ID is not matching to selected key fields." },
		{ "DialogAddRelationshipOnDatamodel9", "Failed to specify an existing key on the target table. Define FK and relationship manualy." },
		{ "DialogAddRelationshipOnDatamode20", "Name or ID of field to be pasted is duplicated in the target table." },
		{ "DialogCreateTableStatement01", "CREATE TABLE Statements" },
		{ "DialogCreateTableStatement02", "File name" },
		{ "DialogCreateTableStatement03", "Table name as" },
		{ "DialogCreateTableStatement04", "Table name on definitions" },
		{ "DialogCreateTableStatement05", "Table ID on definitions" },
		{ "DialogCreateTableStatement06", "Comment line" },
		{ "DialogCreateTableStatement07", "Section separator" },
		{ "DialogCreateTableStatement08", "Note that conditional relationships will not be translated as FK constraints. They should be implemented as codes in data processing programs." },
		{ "DialogCreateTableStatement09", "Output" },
		{ "DialogCreateTableStatement10", "Set" },
		{ "DialogCreateTableStatement11", "Add COMMENT to fields with Alias" },
		{ "DialogDataflowLine01", "Node#1" },
		{ "DialogDataflowLine02", "Flow Direction" },
		{ "DialogDataflowLine06", "Information" },
		{ "DialogDataflowLine07", "Sheet" },
		{ "DialogDataflowLine08", "Sheets" },
		{ "DialogDataflowLine09", "Box" },
		{ "DialogDataflowLine10", "Box,sheet" },
		{ "DialogDataflowLine11", "Box,sheets" },
		{ "DialogDataflowLine12", "Flat box" },
		{ "DialogDataflowLine13", "F.box,sheet" },
		{ "DialogDataflowLine14", "F.box,sheets" },
		{ "DialogDataflowLine15", "Timber" },
		{ "DialogDataflowLine16", "Timber,sheet" },
		{ "DialogDataflowLine17", "Timber,sheets" },
		{ "DialogDataflowLine18", "Cylinder" },
		{ "DialogDataflowLine19", "Cyl.,sheet" },
		{ "DialogDataflowLine20", "Cyl.,sheets" },
		{ "DialogDataflowLine21", "Body" },
		{ "DialogDataflowLine22", "Body,sheet" },
		{ "DialogDataflowLine23", "Body,sheets" },
		{ "DialogDataflowLine24", "Body, flat box" },
		{ "DialogDataflowLine25", "Body,box,sheet" },
		{ "DialogDataflowLine26", "Cancel" },
		{ "DialogDataflowLine27", "Name of Flow" },
		{ "DialogDataflowLine28", "Icon of Flow" },
		{ "DialogDataflowLine29", "Node#2" },
		{ "DialogDataflowLine30", "Slide Seq." },
		{ "DialogDataflowLine31", "(extention)" },
		{ "DialogDataflowLine32", "Add Flow" },
		{ "DialogDataflowLine33", "Change Flow" },
		{ "DialogDataflowNode01", "Label" },
		{ "DialogDataflowNode02", "Type" },
		{ "DialogDataflowNode03", "Ledger" },
		{ "DialogDataflowNode04", "Shelf Stocker" },
		{ "DialogDataflowNode05", "Floor Stocker" },
		{ "DialogDataflowNode06", "Tray" },
		{ "DialogDataflowNode07", "File Box" },
		{ "DialogDataflowNode08", "Subject/System" },
		{ "DialogDataflowNode09", "Cash Register" },
		{ "DialogDataflowNode10", "Safe" },
		{ "DialogDataflowNode11", "Waiting Room" },
		{ "DialogDataflowNode12", "Slide Seq." },
		{ "DialogDataflowNode13", "Cancel" },
		{ "DialogDataflowNode14", "Process" },
		{ "DialogDataflowNode15", "Add Node" },
		{ "DialogDataflowNode16", "Change Node" },
		{ "DialogDataflowNode17", "Change Process" },
		{ "DialogDataflowNode18", "Basket" },
		{ "DialogDataflowNode19", "Drum" },
		{ "DialogDataflowNode20", "Descriptions" },
		{ "DialogDataflowNode21", "Event Position" },
		{ "DialogDataflowNode22", "LEFT" },
		{ "DialogDataflowNode23", "RIGHT" },
		{ "DialogDataflowNode24", "(extention)" },
		{ "DialogDocuments01", "Subsystem" },
		{ "DialogDocuments02", "Document Type" },
		{ "DialogDocuments03", "Table definition" },
		{ "DialogDocuments04", "Function definition" },
		{ "DialogDocuments05", "The composition of ID and name of table/function will be the name of 'Sheet'. Note that each name of 'Sheet' has to be unique in a 'Book' and some letters(*,:,?,[,],/) should not used as name of 'Sheet'.　" },
		{ "DialogDocuments06", "Background colors and font colors of panel images will be ignored in Function Doc." },
		{ "DialogDocuments07", "Generate" },
		{ "DialogDocuments08", "Close" },
		{ "DialogDocuments09", "Generate Documents" },
		{ "DialogDocuments10", "* Select one of the listed" },
		{ "DialogDocuments11", " definitions are generated with the name as -" },
		{ "DialogDocuments12", " definitions are not generated. Check if theres any duplications of ID and name of definitions." },
		{ "DialogDocuments13", "Arial" },
		{ "DialogDocuments14", "Arial" },
		{ "DialogDocuments15", "Lucida Console" },
		{ "DialogDocuments16", "FUNCTION DOC" },
		{ "DialogDocuments17", "Subsystem Name" },
		{ "DialogDocuments18", "Function Name" },
		{ "DialogDocuments19", "Function Type" },
		{ "DialogDocuments20", "Summary" },
		{ "DialogDocuments21", "Parameters" },
		{ "DialogDocuments22", "Return" },
		{ "DialogDocuments23", "Descriptions" },
		{ "DialogDocuments24", "IO List" },
		{ "DialogDocuments25", "IO Name" },
		{ "DialogDocuments26", "IO Type" },
		{ "DialogDocuments27", "Panel" },
		{ "DialogDocuments28", "Spool" },
		{ "DialogDocuments29", "Page" },
		{ "DialogDocuments30", "Functions Used by this" },
		{ "DialogDocuments31", "Launch Event" },
		{ "DialogDocuments32", "Functions Using this" },
		{ "DialogDocuments33", "Tasks using this function" },
		{ "DialogDocuments34", "Role Name" },
		{ "DialogDocuments35", "Task Name" },
		{ "DialogDocuments36", "Action" },
		{ "DialogDocuments37", "IO Definition" },
		{ "DialogDocuments38", "IO Type" },
		{ "DialogDocuments39", "IO Image" },
		{ "DialogDocuments40a", "Refer to the file " },
		{ "DialogDocuments40b", "" },
		{ "DialogDocuments41", "Label" },
		{ "DialogDocuments42", "Column Name" },
		{ "DialogDocuments43", "Column Type" },
		{ "DialogDocuments44", "INPUT" },
		{ "DialogDocuments45", "REQUIRED" },
		{ "DialogDocuments46", "OUTPUT" },
		{ "DialogDocuments47", "CONTROLS" },
		{ "DialogDocuments48", "Field" },
		{ "DialogDocuments49", "Data Type" },
		{ "DialogDocuments50", "Operations" },
		{ "DialogDocuments51", "TABLE DOC" },
		{ "DialogDocuments52", "Table Name" },
		{ "DialogDocuments53", "Table Type" },
		{ "DialogDocuments54", "Field List" },
		{ "DialogDocuments55", "Field Name" },
		{ "DialogDocuments56", "Data Type" },
		{ "DialogDocuments57", "Default" },
		{ "DialogDocuments58", "NO" },
		{ "DialogDocuments59", "OK" },
		{ "DialogDocuments60", "Key Definitions List" },
		{ "DialogDocuments61", "Key Type" },
		{ "DialogDocuments62", "Field List" },
		{ "DialogDocuments63", "Primary Key" },
		{ "DialogDocuments64", "Foreigh Key" },
		{ "DialogDocuments65", "Secondary Key" },
		{ "DialogDocuments66", "Functions List" },
		{ "DialogDocuments67", "Key Definition" },
		{ "DialogDocuments68", "Relationship Type" },
		{ "DialogDocuments69", "Table Name" },
		{ "DialogDocuments70", "Relationship Key" },
		{ "DialogDocuments71", "FAMILY" },
		{ "DialogDocuments72", "REFFER" },
		{ "DialogDocuments73", "SUBTYPE" },
		{ "DialogScan01", "Scan/Replace String" },
		{ "DialogScan02", "Scanning" },
		{ "DialogScan03", "Replacing" },
		{ "DialogScan04", "Case Sensitive" },
		{ "DialogScan05", "Scanning" },
		{ "DialogScan06", "System" },
		{ "DialogScan07", "Departments" },
		{ "DialogScan08", "Table types" },
		{ "DialogScan09", "Data types" },
		{ "DialogScan10", "Function types" },
		{ "DialogScan11", "Maintenance logs" },
		{ "DialogScan12", "Subject areas" },
		{ "DialogScan13", "Roles" },
		{ "DialogScan14", "Tasks" },
		{ "DialogScan15", "Subsystems" },
		{ "DialogScan16", "Tables" },
		{ "DialogScan17", "Functions" },
		{ "DialogScan18", "Start Scan" },
		{ "DialogScan19", "sel" },
		{ "DialogScan20", "Element" },
		{ "DialogScan21", "Name" },
		{ "DialogScan22", "Attribute" },
		{ "DialogScan23", "Value" },
		{ "DialogScan24", "Hit" },
		{ "DialogScan25", "Close" },
		{ "DialogScan26", "Task Type" },
		{ "DialogScan28", "Replace all selected" },
		{ "DialogScan29", "Output List" },
		{ "DialogScan30", "(All Tasks)" },
		{ "DialogScan31", "(All Subsystems)" },
		{ "DialogScan32", " elements with " },
		{ "DialogScan33", " of strings were found. Select any row to see detail value." },
		{ "DialogScan34", "None of elements was found with the string." },
		{ "DialogScan35", "System" },
		{ "DialogScan36", "Department" },
		{ "DialogScan37", "Table type" },
		{ "DialogScan38", "Data type" },
		{ "DialogScan39", "Function type" },
		{ "DialogScan40", "Maintenance log" },
		{ "DialogScan41", "Subject area" },
		{ "DialogScan42", "Subject area /Process" },
		{ "DialogScan43", "Subject area /Flow" },
		{ "DialogScan44", "Role" },
		{ "DialogScan45", "Task" },
		{ "DialogScan46", "Task /Action" },
		{ "DialogScan47", "Task /Action /UI" },
		{ "DialogScan48", "Subsystem" },
		{ "DialogScan49", "Subsystem /Model" },
		{ "DialogScan50", "Table" },
		{ "DialogScan51", "Table /Field" },
		{ "DialogScan52", "Function" },
		{ "DialogScan53", "Function /Launch event" },
		{ "DialogScan54", "Function /Panel" },
		{ "DialogScan55", "Function /Panel item" },
		{ "DialogScan56", "Function /Web page" },
		{ "DialogScan57", "Function /Web page item" },
		{ "DialogScan58", "Function /Spool" },
		{ "DialogScan59", "Function /Spool item" },
		{ "DialogScan60", "Function /Table" },
		{ "DialogScan61", "Function /Table field" },
		{ "DialogScan62", "ID" },
		{ "DialogScan63", "Name" },
		{ "DialogScan64", "Name extention" },
		{ "DialogScan65", "Executed if" },
		{ "DialogScan66", "Label" },
		{ "DialogScan67", "Instance" },
		{ "DialogScan68", "Log headder" },
		{ "DialogScan69", "Descriptions" },
		{ "DialogScan70", "Event" },
		{ "DialogScan71", "Alias" },
		{ "DialogScan72", "Default" },
		{ "DialogScan73", "Constraint" },
		{ "DialogScan74", "Launch event" },
		{ "DialogScan75", "Operations" },
		{ "DialogScan76", "Summary" },
		{ "DialogScan77", "Parameters" },
		{ "DialogScan78", "Return" },
		{ "DialogScan79", "User interface" },
		{ "DialogScan80", "Relationship" },
		{ "DialogScan81", " elements with " },
		{ "DialogScan82", " strings were replaced." },
		{ "DialogScan83", "Descriptions of Datamodel" },
		{ "DialogImportXEAD01", "Import Definitions from XEAD File" },
		{ "DialogImportXEAD02", "File to import" },
		{ "DialogImportXEAD03", "System to import" },
		{ "DialogImportXEAD04", "Definition Type" },
		{ "DialogImportXEAD05", "Tables and Functions" },
		{ "DialogImportXEAD06", "Task Definitions" },
		{ "DialogImportXEAD07", "Import" },
		{ "DialogImportXEAD08", "Close" },
		{ "DialogImportXEAD09", "Subsystem to import" },
		{ "DialogImportXEAD10", "Target Subsystem" },
		{ "DialogImportXEAD11", "Definitions of Tables and Functions in the specified subsystem will be imported into the target. Each of definitions are identified by their ID(seq). Those definitions which ID is not found in the target will be appended. Note that unexpected update may occur if ID of definitions are duplicated in the target. Reffer to HELP before you execute." },
		{ "DialogImportXEAD12", "(Select)" },
		{ "DialogImportXEAD13", "Role to import" },
		{ "DialogImportXEAD14", "Target Role" },
		{ "DialogImportXEAD15", "Definitions of Tasks in the specified role will be imported into the target. Each of definitions are identified by their ID(seq). Those definitions which ID is not found in the target will be appended. Note that unexpected update may occur if ID of definitions are duplicated in the target. Reffer to HELP before you execute." },
		{ "DialogImportXEAD16", "Table: " },
		{ "DialogImportXEAD17", " definition(s) were updated and " },
		{ "DialogImportXEAD18", " definition(s) were appended and " },
		{ "DialogImportXEAD19", "Function: " },
		{ "DialogImportXEAD20", "" },
		{ "DialogImportXEAD21", " Table(s) were not found as IO-table of Functions." },
		{ "DialogImportXEAD22", "" },
		{ "DialogImportXEAD23", " Function(s) were not found as Function-called by imported Functions." },
		{ "DialogImportXEAD24", "Task: " },
		{ "DialogImportXEAD25", "" },
		{ "DialogImportXEAD26", " Panel/Spool(s) were not found as Function's IO used in imported Task actions." },
		{ "DialogImportXEAD27", "" },
		{ "DialogImportXEAD28", " Table Key(s) were not found in the target to define Table Relationship." },
		{ "DialogImportXEAD29", "Refer to the Log named as " },
		{ "DialogImportXEAD30", "." },
		{ "DialogImportXEAD31", "Target File" },
		{ "DialogImportXEAD32", "Target System" },
		{ "DialogImportXEAD33", "A definition in the target was identified and updated." },
		{ "DialogImportXEAD34", "A new definition was copied and created in the target." },
		{ "DialogImportXEAD35", " - A relationship for these tables was not imported, because one of key definitions required was not found in the target system." },
		{ "DialogImportXEAD36", " - A relationship for these tables was copied and created in the target." },
		{ "DialogImportXEAD37", "'s definition is missing in the target, therefore Table IO definition was not imported for the Function above." },
		{ "DialogImportXEAD38", "'s definition is missing in the target, therefore Function-called-from definition was not imported for " },
		{ "DialogImportXEAD39", "." },
		{ "DialogImportXEAD40", "'s definition is missing in the target, therefore Panel/Spool usage was not imported for the Task above." },
		{ "DialogImportXEAD41", "(File could have been renamed to save changes)" },
		{ "DialogImportXEAD42", " is missing in the target system which is refered to by the subsystem as 'External Table'." },
		{ "DialogImportXEAD43", "As the table has one or some relationships related to its PK, import has skipped to change field elements of PK." },
		{ "DialogImportXEAD44", "Functions" },
		{ "DialogImportXEAD45", "Definitions of Functions in the specified subsystem will be imported into the target. Each of definitions are identified by their ID(seq). Those definitions which ID is not found in the target will be appended. Note that unexpected update may occur if ID of definitions are duplicated in the target. Reffer to HELP before you execute." },
		{ "DialogImportXEAD46", "Tables" },
		{ "DialogImportXEAD47", "Definitions of Tables in the specified subsystem will be imported into the target. Each of definitions are identified by their ID(seq). Those definitions which ID is not found in the target will be appended. Note that unexpected update may occur if ID of definitions are duplicated in the target. Reffer to HELP before you execute." },
		{ "DialogImportXEAD48", "Importing was canceled as a corresponding definition exists in the subsystem where is not the one specified to be imported into." },
		{ "DialogImportXEAD49", "Importing was canceled as a corresponding definition exists in the role where is not the one specified to be imported into." },
		{ "DialogImportXEAD50", " definition(s) were not imported." },
		{ "DialogImportXEAD51", "If Data-flow has any process(task) which is not defined in target sysytem, importing will be canceled. Note that unexpected update may occur if ID of definitions are duplicated in the target. Reffer to HELP before you execute." },
		{ "DialogImportXEAD52", "Data-Flow to import" },
		{ "DialogImportXEAD53", "Target Data-Flow" },
		{ "DialogImportXEAD54", "Importing was canceled as a corresponding definition is missing in the target system." },
		{ "DialogImportXEAD55", "Importing Data-Flow succeeded." },
		{ "DialogImportXEAD56", "Importing Data-flow failed. " },
		{ "DialogImportSQL01", "Import CreateTable Statements" },
		{ "DialogImportSQL02", "File to import" },
		{ "DialogImportSQL03", "Target Subsystem" },
		{ "DialogImportSQL04", "RecordCreateDTTM,RecordUpdateDTTM,RecordCreateUser,RecordUpdateUser,DeleteFlag" },
		{ "DialogImportSQL05", "Import" },
		{ "DialogImportSQL06", "Close" },
		{ "DialogImportSQL07", "(Select)" },
		{ "DialogImportSQL08", " table(s) and " },
		{ "DialogImportSQL09", " relationship(s) were parsed and imported." },
		{ "DialogImportSQL10", "Set XEAD data types according to SQL data types." },
		{ "DialogImportSQL11", "Set fields with following names as hidden on datamodel." },
		{ "DialogImportSQL12", "Set table ID automatically according to import order." },
		{ "DialogImportSQL13", "Set field name in field ID(alias)." },
		{ "DialogImportSQL14", "Set COMMENT value in field Name" },
		{ "S1", "Format Version of this XEAD content file is " },
		{ "S2", ". Format Version this application can handle with is upto " },
		{ "S3", ". Please use the latest application." },
		{ "S4", "Inconsistency has been found in TableIO definition. Save now as XEAD will rocover the inconsistency." },
		{ "S10", " is newly registered." },
		{ "S11", " is editted." },
		{ "S12", " is deleted." },
		{ "S49", "System Name" },
		{ "S50", "File" },
		{ "S51", "New" },
		{ "S52", "Open" },
		{ "S53", "Exit" },
		{ "S54", "Print Format" },
		{ "S55", "Print" },
		{ "S56", "Save" },
		{ "S57", "Save As" },
		{ "S58", "Edit" },
		{ "S59", "Undo changes in node" },
		{ "S60", "Redo changes in node" },
		{ "S61", "Scan" },
		{ "S62", "Scan/Replace String" },
		{ "S63", "Add/Remove Bookmarks" },
		{ "S64", "Import" },
		{ "S65", "XEAD Definitions(*.xead)" },
		{ "S66", "CreateTable Statements(*.sql;txt)" },
		{ "S73", "Jump to bookmark" },
		{ "S74", "Matrics List" },
		{ "S75", "Subject area * Task" },
		{ "S76", "Subject area * Function" },
		{ "S77", "Task * Function" },
		{ "S78", "Task * Table" },
		{ "S79", "Table * Function" },
		{ "S80", "v" },
		{ "S81", "Matrix List is generated with the name as -" },
		{ "S82", "Generate Documents" },
		{ "S83", "Tool" },
		{ "S84", "Generate Task List" },
		{ "S85", "Generate Table List" },
		{ "S86", "Generate Function List" },
		{ "S87", "Generate CreateTableSQL" },
		//{ "S88", "Generate Protocol List" },
		{ "S89", "Jump to URL" },
		{ "S90", "Help" },
		{ "S91", "XEAD Help" },
		{ "S92", "About XEAD" },
		{ "S94", "File(F)" },
		{ "S95", "Edit(E)" },
		{ "S96", "Scan(S)" },
		{ "S97", "Tool(T)" },
		{ "S98", "Help(H)" },
		{ "S99", "Generate Field List" },
		{ "S100", "Add child-node" },
		{ "S101", "Add child-node(in list)" },
		{ "S102", "Paste child-node" },
		{ "S103", "Copy" },
		{ "S104", "Cut" },
		{ "S105", "Delete" },
		{ "S106", "Add child-node" },
		{ "S107", "Panel" },
		{ "S108", "Spool" },
		{ "S109", "WEB Page" },
		{ "S110", "Foreign Key" },
		{ "S111", "Secondary Key" },
		{ "S132", "Change Letter Size" },
		{ "S133", "Change Form Size" },
//		{ "S134", "Small" },
//		{ "S135", "Medium" },
//		{ "S136", "Large" },
		{ "S137", "Change Form Color" },
		{ "S150", "Change Background Color" },
		{ "S163", "Change Foreground Color" },
		{ "S176", "Undo" },
		{ "S177", "Redo" },
		{ "S178", "Cut" },
		{ "S179", "Copy" },
		{ "S180", "Paste" },
		{ "S181", "Delete" },
		{ "S182", "Select All" },
		{ "S183", "Underline" },
		{ "S184", "Reset decorations" },
		{ "S185", "Generate Image data" },
		{ "S186", "Cancel underline" },
		{ "S187", "Block select" },
		{ "S189", "System Name" },
		{ "S190", "Search Image File" },
		{ "S192", "Version" },
		{ "S195", "Descriptions" },
		{ "S196", "Section List" },
		{ "S198", "Section Name" },
		{ "S201", "ID(seq.)" },
		{ "S204", "Descriptions" },
		{ "S206", "Table Type List" },
		{ "S208", "Table Type Name" },
		{ "S209", "Task Type List" },
		{ "S210", "Task Type Name" },
		{ "S216", "Data Type List" },
		{ "S218", "Data Type Name" },
		{ "S223", "SQL Exp." },
		{ "S227", "Basic Type" },
		{ "S237", "Length" },
		{ "S240", "Decimal" },
		{ "S242", "Function Type List" },
		{ "S244", "Function Type" },
		{ "S252", "Amendments" },
		{ "S254", "Version" },
		{ "S257", "Amend. Date Time" },
		{ "S260", "Amendments" },
		{ "S265", "Section Name" },
		{ "S271", "Role Name" },
		{ "S277", "Table Type Name" },
		{ "S283", "Table Name" },
		{ "S284", "Subsystem Name" },
		{ "S289", "Data Type Name" },
		{ "S290", "Basic Type" },
		{ "S291", "Length" },
		{ "S292", "Decimal" },
		{ "S293", "SQL Exp." },
		{ "S297", "ID(alias)" },
		{ "S298", "Field Name" },
		{ "S299", "Table Name" },
		{ "S300", "Subsystem Name" },
		{ "S305", "Function Type Name" },
		{ "S311", "Function Name" },
		{ "S312", "Subsystem Name" },
		{ "S313", "Parameters" },
		{ "S317", "Date Time" },
		{ "S318", "Version" },
		{ "S319", "Amendments" },
		{ "S324", "Job Flow Name" },
		{ "S339", "Role" },
		{ "S340", "Role Name" },
		{ "S341", "Section" },
		{ "S348", "Role Name" },
		{ "S356", "Section" },
		{ "S359", "Tasks" },
		{ "S360", "Task Name" },
		{ "S361", "Event" },
		{ "S362", "Task Type" },
		{ "S363", "Task Name" },
		{ "S368", "EVENT means the situation when this task should be started." },
		{ "S372", "Task Name" },
		{ "S375", "Protocol" },
		{ "S380", "Related Job Flow" },
		{ "S390", "Remarks" },
		{ "S391", "Condition" },
		{ "S392", "If neccessary, specify condition to execute this action." },
		{ "S394", "Action" },
		{ "S400", "Operations" },
		{ "S403", "Descriptions of IO Image" },
		{ "S407", "Subsystem List" },
		{ "S408", "Functions Structure View" },
		{ "S411", "Event to Run" },
		{ "S413", "Subsystem" },
		{ "S415", "Function Name" },
		{ "S417", "Function Type" },
		{ "S419", "Summary" },
		{ "S421", "Param./Return" },
		{ "S436", "Subsystem Name" },
		{ "S437", "T." },
		{ "S438", "F." },
		{ "S439", "exC" },
		{ "S440", "exR" },
		{ "S441", "exU" },
		{ "S442", "exD" },
		{ "S443", "exF." },
		{ "S448", "Table ID" },
		{ "S449", "Table IO Name" },
		{ "S464", "Table List" },
		{ "S465", "External Table List" },
		{ "S466", "Datamodel" },
		{ "S467", "Descriptions of Datamodel" },
		{ "S471", "Table Name" },
		{ "S472", "Model" },
		{ "S477", "Table Type" },
		{ "S478", "Primary Key" },
		{ "S479", "exC" },
		{ "S480", "exR" },
		{ "S481", "exU" },
		{ "S482", "exD" },
		{ "S483", "show" },
		{ "S490", "Model" },
		{ "S495", "Table Type" },
		{ "S496", "Primary Key" },
		{ "S502", "Type" },
		{ "S508", "Primary Key" },
		{ "S518", "CREATE TABLE(SQL)" },
		{ "S519", "Functions Using this" },
		{ "S520", "External Functions Using this" },
		{ "S523", "Function Name" },
		{ "S532", "Function Name" },
		{ "S540", "Seq." },
		{ "S542", "Field Name" },
		{ "S543", "Attr.Type" },
		{ "S544", "Data Type" },
		{ "S546", "Default" },
		{ "S547", "Model" },
		{ "S550", "New" },
		{ "S554", "Attr.Type" },
		{ "S556", "Type" },
		{ "S558", "Native" },
		{ "S559", "NATIVE Attribute Field" },
		{ "S561", "Inherited" },
		{ "S562", "INHERITED Attribute Field" },
		{ "S564", "Derived" },
		{ "S565", "DERIVED Attribute Field" },
		{ "S569", "Default" },
		{ "S577", "Field Name" },
		{ "S583", "Show on Model" },
		{ "S585", "If checked, field name appears on Table Box of Datamodel" },
		{ "S586", "(No descriptions)" },
		{ "S592", "Function Name" },
		{ "S597", "Operations to Field" },
		{ "S602", "Function Name" },
		{ "S607", "Operations to Field" },
		{ "S612", "Type" },
		{ "S613", "Field List" },
		{ "S616", "KEY Type" },
		{ "S624", "Relationship List" },
		{ "S632", "Function List" },
		{ "S633", "External Function List" },
		{ "S638", "Function Name" },
		{ "S639", "Function Type" },
		{ "S640", "Summary" },
		{ "S641", "Parameters" },
		{ "S642", "Return Value" },
		{ "S647", "Function ID" },
		{ "S648", "Function Name" },
		{ "S649", "Function Type" },
		{ "S650", "Summary" },
		{ "S662", "Type" },
		{ "S664", "Function Name" },
		{ "S666", "Param./Return" },
		{ "S668", "Summary" },
		{ "S673", "IO List" },
		{ "S674", "Functions Used by this" },
		{ "S675", "Functions Using this" },
		{ "S676", "Tasks Using this" },
		{ "S680", "IO Name" },
		{ "S688", "Function Name" },
		{ "S689", "Event to run" },
		{ "S693", "IO Name" },
		{ "S694", "Role Name" },
		{ "S696", "Task Name" },
		{ "S697", "Action" },
		{ "S701", " Panel Image" },
		{ "S703", "Panel Name" },
		{ "S717", "Spool Name" },
		{ "S727", " Spool Image" },
		{ "S739", "Primary Key" },
		{ "S742", "Extention Name" },
		{ "S745", "CRUD" },
		{ "S761", "Jump to Table Definition" },
		{ "S766", " Page Image" },
		{ "S768", "Page Name" },
		{ "S774", "File Name" },
		{ "S783", "Exit" },
		{ "S782", "Create a new file and open" },
		{ "S781", "Select file and open" },
		{ "S784", "Choose action to specify file to be processed" },
		{ "S785", "XEAD Modeler - Select Content File" },
		{ "S786", "Open existing content file" },
		{ "S789", "Create a new file and open" },
		{ "S788", "XEAD Modeler - Specity name of content file" },
		{ "S794", "It failed to parse xead file specified. Check format of file." },
		{ "S798", "File with specified name and the valid extention is not found." },
		{ "S799", "Extention of the file is invalid." },
		{ "S800", "This action has sub-actions.　Copy them?" },
		{ "S801", "Copy Option of Task-Action" },
		{ "S806", "Cancel" },
		{ "S805", "Specify file name again" },
		{ "S804", "Replace" },
		{ "S807", "Specified file is existing. You may replace it?" },
		{ "S808", "XEAD Modeler - Select Content File" },
		{ "S811", "Specified is a Read-Only file. Note that you" },
		{ "S813", "can not save what you have editted with XEAD." },
		{ "S860", "Add" },
		{ "S861", "Add Panel" },
		{ "S862", "Add Spool" },
		{ "S863", "Add WEB Page" },
		{ "S864", "Add Foreign Key" },
		{ "S865", "Add Secondary Key" },
		{ "S866", "Copy" },
		{ "S867", "Paste" },
		{ "S868", "Delete" },
		{ "S869", "Remove" },
		{ "S870", "Move ↑" },
		{ "S871", "Move ↓" },
		{ "S872", "Move ←" },
		{ "S873", "Move →" },
		{ "S874", "Jump" },
		{ "S875", "Start Slide Show" },
		{ "S876", "Set Slide Sequences" },
		{ "S877", "Adjust Table Positions" },
		{ "S878", "Generate Image Data" },
		{ "S879", "Tips to Edit" },
		{ "S880", "Generate List Data" },
		{ "S881", "Reload" },
		{ "S882", "Adjust Table Widths" },
		{ "S915", "Add Node" },
		{ "S916", "Paste Node" },
		{ "S919", "Operations" },
		{ "S993", "What is KEY?" },
		{ "S1000", "XEAD Modeler - Save Replacing" },
		{ "S1001", "Do you save what you have processed?" },
		{ "S1002", "Current content has been changed. You need to save before scanning." },
		{ "S1098", "Save and Exit" },
		{ "S1099", "Exit without saving" },
		{ "S1100", "Back to XEAD" },
		{ "S1101", "Do you save what you have changed?" },
		{ "S1102", "XEAD Modeler - Save Change" },
		{ "S1103", "Save and Create a New File" },
		{ "S1104", "Create a New File without saving" },
		{ "S1106", "Do you save changes before creating a new file?" },
		{ "S1107", "XEAD Modeler - Save Changes and Create New" },
		{ "S1108", "XEAD Modeler - Save Changes by Importing" },
		{ "S1109", "Create New and Open" },
		{ "S1110", "Do you save changes?" },
		{ "S1111", "Save changes" },
		{ "S1112", "Save as other name" },
		{ "S1113", "Cancel changes" },
		{ "S1114", "Save and Open" },
		{ "S1115", "Open without Saving" },
		{ "S1116", "Current content has been changed. You need to save before importing." },
		{ "S1117", "Current content has been changed. Do you save changes and open?" },
		{ "S1118", "Save Changes" },
		{ "S1119", "Open existing xead file" },
		{ "S1120", "Open existing xead file to import" },
		{ "S1121", "Open CreateTable text-file(txt;sql) to import" },
		{ "S1125", "Save As" },
		{ "S1149", "Saving failed." },
		{ "S1225", "No.,Role ID,Role Name,Section,Task ID,Task Name,Event,Task Type ID,Task Type Name" },
		{ "S1242", "XEAD Modeler - Specify name of CSV file for Task List." },
		{ "S1247", "No task definitions found to be listed" },
		{ "S1250", "No.,Subsystem ID,Subsystem Name,Table ID,Table Name,C,R,U,D,Type,Primary " +
		"Key,exC,exR,exU,exD," },
		{ "S1251", "No.,Subsystem ID,Subsystem Name,Table ID,Table Name,Key,Field ID,Field Name,Attribute,Data Type,Null,Default,Model,Descriptions" },
		{ "S1310", "XEAD Modeler - Specify name of CSV file for Table List." },
		{ "S1315", "No table definitions found to be listed" },
		{ "S1319", "No.,Subsystem ID,Subsystem Name,Function ID,Function Name,Type,Summary,Related " +
		"Task" },
		{ "S1347", ") >" },
		{ "S1343", "<" },
		{ "S1348", "etc." },
		{ "S1350", "none" },
		{ "S1353", "XEAD Modeler - Specify name of CSV file for Function List." },
		{ "S1358", "No function definitions found to be listed" },
		{ "S1360", "XEAD Modeler - Specify name of text file for CREATE statements." },
		{ "S1366", "Warning: Incoherency of data type in key fields is found." },
		{ "S1368", "Check data type of those fields marked with (?) in FOREIGN KEY statement." },
		{ "S1370", "For further information, refer to HELP document." },
		{ "S1371", "No table definitions found to be processed" },
		{ "S1372", "Statements are generated in the file named as" },
		{ "S1582", "XEAD Modeler - Specify name of CSV file for task protocol list." },
		{ "S1587", "Role," },
		{ "S1593", "Task," },
		{ "S1599", "Event," },
		{ "S1600", ", " },
		{ "S1613", "No task definitions found to be processed" },
		{ "S1617", "> pointed by cursor is not valid as URL." },
		{ "S1618", "String <" },
		{ "S1621", "It has to start with http: or file:, and also has to end" },
		{ "S1623", "with , or ; or )." },
		{ "S1629", "> is not found in the folder." },
		{ "S1628", "HELP file <" },
		{ "S1735", "Choose CSV file to be processed" },
		{ "S1747", "CSV format is invalid. Refer to HELP to check due format." },
		{ "S1748", "Some rows/columns were not processed. Refer to HELP to check due " +
		"format." },
		{ "S1770", "Specify width and height of the form in order." },
		{ "S1772", "You can also adjust the size by dragging right" },
		{ "S1774", "or bottom side of the form using pointing device." },
		{ "S1779", "Specify width and height of the form in order." },
		{ "S1797", "(Root of Functions Structure)" },
		{ "S1829", "File name of IO definition is invalid." },
		{ "S1845", "Table IO" },
		{ "S1847", "> (Page " },
		{ "S1846", "Job Flow <" },
		{ "S1920", "Warning：Table relationship related to this field already exists. " +
		"If you change" },
		{ "S1922", "data type of this field, incoherence may occur between key definitions. " +
		"Incoherence" },
		{ "S1924", "is indicated by warning message in Create Table statement." },
		{ "S1959", "XEAD Modeler - Specify name of CSV file for list data." },
		{ "S1976", "Correct file name and retry reloading using popup menu by clicking " +
		"right button of pointing device." },
		{ "S1977", "You can not edit items on this list. These" },
		{ "S1978", "are listed according to definition of tasks" },
		{ "S1979", "which you can edit as required." },
		{ "S1981", "You can not edit items on this list. These" },
		{ "S1983", "are listed according to definition of roles" },
		{ "S1985", "which you can edit as required." },
		{ "S1987", "You can not edit items on this list. These" },
		{ "S1989", "are listed according to definition of tables" },
		{ "S1991", "which you can edit as required." },
		{ "S1993", "You can not edit items on this list." },
		{ "S1995", "are listed according to definition of field" },
		{ "S1997", "which you can edit as required." },
		{ "S1999", "You can not edit items on this list." },
		{ "S2001", "are listed according to definition of functions" },
		{ "S2003", "which you can edit as required." },
		{ "S2005", "Job flow consists of various elements. They are categorized by \'System " +
		"boundary\'," },
		{ "S2007", "\'Process node\', \'Flow\' and \'Storage node\'. You can change size and " +
		"position of" },
		{ "S2009", "System boundary(indicated as white blurred rectangler) by dragging " +
		"its sides. You" },
		{ "S2011", "can add Process node by drag&dropping tree view node of task definition " +
		"into Job Flow." },
		{ "S2013", "In order to add Flow, click right button on name of each Process " +
		"node and select" },
		{ "S2015", "menu item of \'Add Flow\'. If you click right button on somewhere nothing " +
		"placed," },
		{ "S2017", "you can add Storage node by selecting menu item of \'Add Node\'." },
		{ "S2019", "Press key of → to continue, ← to go back to the previous slide." },
		{ "S2021", "With Shift key down and →(←) pressed, the last slide(the first" },
		{ "S2023", "slide) is shown. Press Esc to close slide show." },
		{ "S2025", "If you drag treeview node of <task definition> and drop here," },
		{ "S2027", "the task definition will be changed as one of current role\'s." },
		{ "S2029", "You can not edit IO image here. You need to open the pane of treeview " +
		"node" },
		{ "S2031", "which is located under node of function. You can easily access to " +
		"the pane" },
		{ "S2033", "by selecting item of \'Jump\' on popup menu. In order to add IO image " +
		"for the" },
		{ "S2035", "action, drag-and-drop these nodes into here. Note that XEAD has no " +
		"function" },
		{ "S2037", "to edit WEB page(HTML file)." },
		{ "S2039", "IO images related to the action are defined as treeview nodes(panel/spool/" },
		{ "S2041", "web-page) which located under function definitions. In order to add " +
		"IO image" },
		{ "S2043", "for the action, drag-and-drop these nodes into here." },
		{ "S2045", "These structures are presented according to function definitions." },
		{ "S2047", "Edit them in order to change structures." },
		{ "S2049", "You can not edit IO image here. You need to open the pane of treeview " +
		"node" },
		{ "S2051", "which is located under node of function. You can easily access to " +
		"the pane" },
		{ "S2053", "by selecting item of \'Jump\' on popup menu. Note that XEAD has no " +
		"function" },
		{ "S2055", "to edit WEB page(HTML file)." },
		{ "S2057", "You can change subsystem which tables belong by drag-and-drop treeview " +
		"node" },
		{ "S2059", "of table into this list. Note that even if you move table A from " +
		"subsystem X" },
		{ "S2061", "to Y, table A stays as an \'external\' table in subsystem X." },
		{ "S2063", "By drag&dropping treeview node of <table> which is owned by other " +
		"subsystems into list area," },
		{ "S2065", "it will be registered as a external table of the subsystem. Avoid " +
		"CUD(Create,Update,Delete)" },
		{ "S2067", "operations onto external tables as much as possible in order to increase " +
		"in maintenancibility" },
		{ "S2069", "of subsystems." },
		{ "S2071", "By drag&dropping treeview node of <table> into this area," },
		{ "S2073", "it will appear as a entity box on the datamodel. You can" },
		{ "S2075", "add a relationship lines by drag&dropping key-field in" },
		{ "S2077", "entity-box into table name area. You can also hide relation-" },
		{ "S2079", "ship lines. Reffer to HELP." },
		{ "S2081", "You can not edit information on this list here. They are listed according " +
		"to" },
		{ "S2083", "function difinitions of this subsystem. If you edit \'IO Table\' of " +
		"related" },
		{ "S2085", "functions, this list will change automatically." },
		{ "S2093", "By drag&dropping treeview node of <field> onto this area," },
		{ "S2095", "copy of definition will be added. This operation is quicker" },
		{ "S2097", "than copy-and-paste. Drag the row on this list to change order" },
		{ "S2098", "of the fields listed." },
		{ "S2111", "Each table requires one primary key. If you add a new table definition," },
		{ "S2113", "primary key will be automatically defined for the table. You can " +
		"add" },
		{ "S2115", "not primary keys but secondary keys or foreign keys. Identical values " +
		"of" },
		{ "S2117", "primary key and secondary key are not permitted in the table. And " +
		"value of" },
		{ "S2119", "foreign key must be defined in the table related. Refer to HELP for " +
		"detail." },
		{ "S2121", "By drag&dropping treeview node of <field> onto this area, the field" },
		{ "S2123", "will be joinned to the key. Note that the field joinned to the key" },
		{ "S2125", "should be defined as one owned by this table. You can change the order" },
		{ "S2126", "of key fields by dragging row of this list." },
		{ "S2127", "By drag&dropping treeview node of <key> onto this area, new definition " +
		"of" },
		{ "S2129", "table relationship will be generated. Note that combination of key " +
		"definitions" },
		{ "S2131", "is very restricted. You have to define carefully data type and number " +
		"of fields" },
		{ "S2133", "which consist of these keys. Refer to HELP for details." },
		{ "S2135", "By drag&dropping treeview node of <function> onto this area, it will " +
		"changed as" },
		{ "S2137", "a function owned by this subsystem." },
		{ "S2139", "You can not edit information on this list here. They are listed according " +
		"to" },
		{ "S2141", "difinitions of external functions used by functions of this subsystem." },
		{ "S2143", "Use jump option of popup menu to edit definition of external functions." },
		{ "S2145", "By drag&dropping treeview node of <table> onto this area," },
		{ "S2147", "a new Table IO definition will be generated. You can also" },
		{ "S2149", "copy and add a new IO definition by drag&dropping treeview" },
		{ "S2151", "of <panel IO>, <spool IO>, <table IO> onto this area." },
		{ "S2153", "This operation is quicker than copy-and-pasting these node." },
		{ "S2155", "You can not edit HTML layouts in XEAD. Use external editor to edit " +
		"them." },
		{ "S2157", "By drag&dropping treeview node of <function> onto this area," },
		{ "S2159", "it will be added as a function used by this function. You can change" },
		{ "S2160", "the order of the functions by dragging the row of this list." },
		{ "S2161", "You can not edit information on this list here. They are listed" },
		{ "S2163", "according to difinitions of functions. Use jump option of popup" },
		{ "S2165", "menu to edit them." },
		{ "S2167", "You can not edit information on this list here. They are listed" },
		{ "S2169", "according to difinitions of tasks. Use jump option of popup" },
		{ "S2171", "menu to edit them." },
		{ "S2173", "You can not add nor delete rows on the list here. They are listed" },
		{ "S2175", "according to field list of the table definition. Use the button of " },
		{ "S2177", "\'Jump to Table Definition\' to edit field list." },
		{ "S2184", "New Section" },
		{ "S2185", "New Task Type" },
		{ "S2198", "New Table Type" },
		{ "S2212", "New Data Type" },
		{ "S2235", "New Function Type" },
		{ "S2274", "New Storage" },
		{ "S2286", "If ..." },
		{ "S2288", "Do something" },
		{ "S2300", "Type in ID(listing order), length and name of the new data-type" },
		{ "S2301", "definition. Following is an example." },
		{ "S2302", "CDCustomer,7,Customer Code" },
		{ "S2303", "A data-type definition of specified length will be created. You had" },
		{ "S2304", "better edit other attributes of definition afterward using tab page" },
		{ "S2305", "of \'Data Type List \' on the panel of \'System Definition\'. " },
		{ "S2527", "You can not remove this table as it is used by one or some functions." },
		{ "S2536", "You can not remove fields from this key as it is already related " +
		"to one or some tables." },
		{ "S2539", "You can not delete this section as it owns one or some roles." },
		{ "S2540", "You can not delete this section as at least one definition is required." },
		{ "S2542", "You can not delete this type as it is related to one or some tables." },
		{ "S2543", "You can not delete this type as at least one definition is required." },
		{ "S2545", "You can not delete this type as it is related to one or some fields." },
		{ "S2548", "You can not delete this type as it is related to one or some functions." },
		{ "S2551", "You can not delete this record as at least one is required." },
		{ "S2593", "You can not delete this action as it is the root of action tree." },
		{ "S2612", "Choose image format." },
		{ "S2613", "XEAD Modeler - Image Format" },
		{ "S2617", ")." },
		{ "S2616", "XEAD Modeler - Specify name of image file(" },
		{ "S2623", "Print colors" },
		{ "S2622", "Normal colors" },
		{ "S2624", "Choose color type of Job Flow." },
		{ "S2625", "XEAD Modeler - Color Type" },
		{ "S2629", "Choose color type of Datamodel" },
		{ "S2865", "\'" },
		{ "S2864", "Jump to \'" },
		{ "S2870", "Jump" },
		{ "S2871", "Add Flow" },
		{ "S2872", "Change" },
		{ "S2873", "Copy" },
		{ "S2874", "Delete" },
		{ "S2875", "Hide" },
		{ "S2876", "Show/Hide Instance" },
		{ "S2877", "Show All Relationship" },
		{ "S2954", "new flow" },
		{ "S3062", " ; Corresponds constantly" },
		{ "S3063", " ; Corresponds in case refferring key is not null" },
		{ "S3221", "(Write example values by field here)" },
		{ "S3248", "Descriptions of System" },
		{ "S3253", "Amendment List" },
		{ "S3268", "Descriptions of Subsystem" },
		{ "S3305", "IO Image" },
		{ "S3307", "IO Field List" },
		{ "S3319", "- " },
		{ "S3320", " [ " },
		{ "S3321", " ] " },
		{ "S3326", " \'" },
		{ "S3327", "\' " },
		{ "S3328", "\' / " },
		{ "S3385", "Job Flows" },
		{ "S3391", "Roles and Tasks" },
		{ "S3401", "Server Modules" },
		{ "S3407", "Table List" },
		{ "S3427", "Key List" },
		{ "S3433", "Function List" },
		{ "S3442", "（Reccursive）" },
		{ "S3485", "[rem]" },
		//{ "S3488", "What is key?" },
		{ "S3528", "new job flow" },
		{ "S3545", "new role" },
		{ "S3562", "new task" },
		{ "S3568", "Any time" },
		{ "S3590", "new subsystem" },
		{ "S3606", "new table" },
		{ "S3651", "new field" },
		{ "S3701", "new function" },
		{ "S3707", "none" },
		{ "S3709", "none" },
		{ "S3721", "new panel" },
		{ "S3722", "These are the descriptions that will be shown on the task definitions if linked." },
		{ "S3723", "These are the descriptions that will be hidden on the task definitions if linked." },
		{ "S3742", "panel field" },
		{ "S3750", "new spool" },
		{ "S3771", "spool field" },
		{ "S3777", "new page" },
		{ "S3792", "page field" },
		{ "S3802", "You can not delete this role as it is in charge of one or some tasks" },
		{ "S3811", "\' and so on(" },
		{ "S3810", "As this task is placed as process node on Job Flow \'" },
		{ "S3812", " in total). " },
		{ "S3814", "You can not delete it." },
		{ "S3820", "You can not delete this subsystem as it has one or some tables." },
		{ "S3824", "You can not delete this subsystem as it has one or some functions." },
		{ "S3830", "You can not delete this table as it is used by one or some functions." },
		{ "S3835", "You can not delete this table as it has relationship to tables." },
		{ "S3844", "\', " },
		{ "S3843", "As this table is defined as a external table of the subsystem \'" },
		{ "S3846", "you can not delete it." },
		{ "S3848", "\'etc.(" },
		{ "S3847", "As this table is defined as a external table of the subsystem \'" },
		{ "S3849", " in total)," },
		{ "S3851", "you can not delete it." },
		{ "S3858", "You can not delete this field as it consists of key(s) of this table." },
		{ "S3866", "You can not delete this field as it is used by function(s). Clear " +
		"operations specified for the function(s)." },
		{ "S3878", "You can not delete Primary Key of tables." },
		{ "S3884", "You can not delete this key as it has table relationships." },
		{ "S3897", "You can not delete this function as it is used by one or some tasks." },
		{ "S3903", "You can not delete this function as it is used by one or some functions." },
		{ "S3911", "You can not delete this panel as it is used by one or some tasks." },
		{ "S3922", "You can not delete this spool as it is used by one or some tasks." },
		{ "S3937", "You can not delete this page as it is used by one or some tasks." },
		{ "S3951", "(Copied)" },
		{ "S4556", "System Definition" },
		{ "S4606", " List" },
		{ "S4623", "Roles List" },
		{ "S4632", " - Tasks List" },
		//{ "S4659", "none" },
		//{ "S4661", "\'" },
		//{ "S4660", "\'" },
		//{ "S4664", " flows in total" },
		//{ "S4663", "\' etc.," },
		//{ "S4662", "\'" },
		{ "S4695", "This action is done by manual with no server function used." },
		{ "S4911", "NATIVE" },
		{ "S4914", "INHERITED" },
		{ "S4917", "DERIVED" },
		{ "S4936", "unaccepted" },
		{ "S4937", "accepted" },
		{ "S5007", "Primary Key(PK)" },
		{ "S5011", "Foreign Key(FK)" },
		{ "S5014", "Secondary Key(SK)" },
		{ "S5032", "Relation Type" },
		{ "S5033", "Cardinality" },
		{ "S5036", "KEY" },
		{ "S5037", "Condition that corresponding instance exists" },
		{ "S5050", "FAMILY" },
		{ "S5051", "1:Multiple" },
		{ "S5052", "(forbidden to specify)" },
		{ "S5055", "REFFER" },
		{ "S5060", "SUBCLASS" },
		{ "S5064", "1:1,0" },
		{ "S5161", "Function Name" },
		{ "S5162", "Parameters" },
		{ "S5163", "Executed When" },
		{ "S5219", "Heading" },
		{ "S5220", "Field Name" },
		{ "S5221", "Field Type" },
		{ "S5226", "GUI Component" },
		{ "S5225", "Display Field" },
		{ "S5224", "Input Required" },
		{ "S5223", "Input Optional" },
		{ "S5269", "Value to be set" },
		{ "S5301", "Operations" },
		{ "S5425", "You can not add this function as it is already related to this definition." },
		{ "S5586", "You can not change key definition as it already has relationships." },
		{ "S5595", "You can not add this field as it is already on key definition." },
		{ "S5600", "Warning: Ad key definition consists of fields with the same data " +
		"type, " },
		{ "S5602", "CreateTable statement may be generated in failure. Refer to HELP " +
		"for" },
		{ "S5604", "further information." },
		{ "S5628", "Action is canceled as an identical relationship already exists." },
		{ "S5631", "Combination of foreign keys is invalid." },
		{ "S5703", "Combination of keys specified is invalid. Check number and data type " +
		"of fields of keys." },
		//{ "S5713", "You can not add this IO as it is already related to the task action." },
		{ "S5728", "You can not add this task process as it is already placed on the " +
		"job flow." },
		{ "S5748", "You can not add this table as it is already placed on the datamodel." },
		{ "S5750", "You can not add this table as it is already related to the subsystem." },
		{ "S5760", "Note：The function had better not to create/update/delete" },
		{ "S5761", "those records in 'external table' in order to control" },
		{ "S5762", "'coupling' between subsystems." },
		{ "S6450", "Changed" },
		{ "SplashMessage0", "Launching XEAD Modeler..." },
		{ "SplashMessage1", "Parsing System Definitions..." },
		{ "XLSFontDTL", "Times New Roman" },
		{ "XLSFontHDR", "Arial" }};
	public Object[][] getContents() {
		return contents;
	}
}