package xeadModeler;

/*
 * Copyright (c) 2015 WATANABE kozo <qyf05466@nifty.com>,
 * All rights reserved.
 *
 * This file is part of X-TEA Modeler.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the XEAD Project nor the names of its contributors
 *       may be used to endorse or promote products derived from this software
 *       without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

public class Res_ko extends java.util.ListResourceBundle {
	private static final Object[][] contents = new String[][]{
		{"DialogAddList01","TXT읽어오기"},
		{"DialogAddList02", "취소"},
		{"DialogAddList03","[서브젝트 영역]을 리스트 형식으로 추가"},
		{"DialogAddList04","서브젝트 영역명"},
		{"DialogAddList05","[직무]를 리스트형식으로 추가"},
		{"DialogAddList06","직무명"},
		{"DialogAddList07","[업무]를 리스트형식으로 추가"},
		{"DialogAddList08","업무명"},
		{"DialogAddList09","[서브시스템]을 리스트형식으로 추가"},
		{"DialogAddList10","서브시스템명"},
		{"DialogAddList11","[테이블]을 리스트형식으로 추가"},
		{"DialogAddList12","테이블명"},
		{"DialogAddList13","[필드]를 리스트형식으로 추가"},
		{"DialogAddList14","필드명"},
		{"DialogAddList15","[기능]을 리스트형식으로 추가"},
		{"DialogAddList16","기능명"},
		{"DialogAddRelationshipOnDatamodel1", "Adding Table-Relationship" },
		{"DialogAddRelationshipOnDatamodel2", "Select option to add table-relationship to the target table. Key fields can be added or existing fields can be reused as Foreign-Key. Value of name and ID of fields to be added should be separated by semicolon(;)." },
		{"DialogAddRelationshipOnDatamodel3", "Paste fields to the target table as foreign key." },
		{"DialogAddRelationshipOnDatamodel4", "Reuse existing fields to setup relationship." },
		{"DialogAddRelationshipOnDatamodel5", "New field name" },
		{"DialogAddRelationshipOnDatamodel6", "New ID(alias)" },
		{"DialogAddRelationshipOnDatamodel7", "Cancel" },
		{"DialogAddRelationshipOnDatamodel8", "Number of name and ID is not matching to selected key fields." },
		{"DialogAddRelationshipOnDatamodel9", "Failed to specify an existing key on the target table. Define FK and relationship manualy." },
		{"DialogAddRelationshipOnDatamode20", "Name or ID of field to be pasted is duplicated in the target table." },
		{"DialogConfigColors01","Appearance" },
		{"DialogConfigColors02","Show Grid" },
		{"DialogConfigColors03","Normal Color" },
		{"DialogConfigColors04","Pale Color" },
		{"DialogConfigColors05","Cancel" },
		{"DialogCreateTableStatement01","CREATE TABLE문의 출력과 설정"},
		{"DialogCreateTableStatement02","출력 파일명"},
		{"DialogCreateTableStatement03","테이블명 설정"},
		{"DialogCreateTableStatement04","테이블명을 그대로 이용한다"},
		{"DialogCreateTableStatement05","Alias를 테이블명으로 한다"},
		{"DialogCreateTableStatement06","코멘트행문자"},
		{"DialogCreateTableStatement07","섹션 구분문자"},
		{"DialogCreateTableStatement08","무조건의 테이블 관련정의만이 키의 제약으로 해석되는 점에 주의해 주세요. 조건이 설정된 테이블관련은 데이터 처리상의 제약으로 실장되어야 합니다."},
		{"DialogCreateTableStatement09","Close"},
		{"DialogCreateTableStatement10","설정"},
		{"DialogCreateTableStatement11","에일리어스 지정 필드에 관해 COMMENT출력"},
		{"DialogCreateTableStatement12","Additional Parameters" },
		{"DialogCreateTableStatement13","Ignore Foreign-Key Constraints" },
		{"DialogCreateTableStatement14","Ignore Warnings of Key Definition" },
		{"DialogDataflowLine01","노드1"},
		{"DialogDataflowLine02","화살표의 방향"},
		{"DialogDataflowLine06","전기신호"},
		{"DialogDataflowLine07","단수전표"},
		{"DialogDataflowLine08","복수전표"},
		{"DialogDataflowLine09","상자"},
		{"DialogDataflowLine10","상자,단수전표"},
		{"DialogDataflowLine11","상자,복수전표"},
		{"DialogDataflowLine12","평평한 상자"},
		{"DialogDataflowLine13","평평한 상자,단수전표"},
		{"DialogDataflowLine14","평평한 상자,복수전표"},
		{"DialogDataflowLine15","각재목"},
		{"DialogDataflowLine16","각재목,단수전표"},
		{"DialogDataflowLine17","각재목,복수전표"},
		{"DialogDataflowLine18","원주"},
		{"DialogDataflowLine19","원주,단수전표"},
		{"DialogDataflowLine20","원주,복수전표"},
		{"DialogDataflowLine21","사람"},
		{"DialogDataflowLine22","사람,단수전표"},
		{"DialogDataflowLine23","사람,복수전표"},
		{"DialogDataflowLine24","사람,평상자"},
		{"DialogDataflowLine25","사람,평상자,단수전표"},
		{"DialogDataflowLine26","취소"},
		{"DialogDataflowLine27","플로우명"},
		{"DialogDataflowLine28","플로우 아이콘"},
		{"DialogDataflowLine29","노드2"},
		{"DialogDataflowLine30","슬라이드 순서"},
		{"DialogDataflowLine31","(2번째 줄)"},
		{"DialogDataflowLine32","플로우 추가"},
		{"DialogDataflowLine33","플로우 변경"},
		{"DialogDataflowLine34","Increment slide numbers of following elements?" },
		{"DialogDataflowLine35","Incrementing Slide Numbers" },
		{"DialogDataflowNode01","라벨"},
		{"DialogDataflowNode02","종류"},
		{"DialogDataflowNode03","장부"},
		{"DialogDataflowNode04","보관소(선반)"},
		{"DialogDataflowNode05","보관소(바닥)"},
		{"DialogDataflowNode06","트레이"},
		{"DialogDataflowNode07","서류함"},
		{"DialogDataflowNode08","서브젝트/시스템"},
		{"DialogDataflowNode09","캐시 레지스터"},
		{"DialogDataflowNode10","금고"},
		{"DialogDataflowNode11","대합실"},
		{"DialogDataflowNode12","슬라이드순서"},
		{"DialogDataflowNode13","취소"},
		{"DialogDataflowNode14","프로세스"},
		{"DialogDataflowNode15","노드 추가"},
		{"DialogDataflowNode16","노드 변경"},
		{"DialogDataflowNode17","프로세스 변경"},
		{"DialogDataflowNode18","바구니"},
		{"DialogDataflowNode19","드럼"},
		{"DialogDataflowNode20","설명"},
		{"DialogDataflowNode21","Event Position" },
		{"DialogDataflowNode22","LEFT" },
		{"DialogDataflowNode23","RIGHT" },
		{"DialogDataflowNode24","(2번째 줄)"},
		{"DialogDocuments01","서브시스템"},
		{"DialogDocuments02","설계서 종류"},
		{"DialogDocuments03","테이블 설계서"},
		{"DialogDocuments04","기능 설계서"},
		{"DialogDocuments05","ID와 명칭의 조합으로 시트명이 설정되었습니다. 시트명이 중복된 정의요소에 관해서는 출력되지 않습니다. 또, 어떤 종류의 기호(*,:,?,[,],/  반각문자, 전각문자등)를 시트명으로 사용하면 파일을 열 때, 경고멧세지가 표시되는 점에 주의해 주시기 바랍니다."},
		{"DialogDocuments06","또한 기능설계서에 있어서 X-TEA Modeler에 등록된 패널이나 스풀의 배경색상 지정은 무시됩니다.(규정명의 이미지 파일이 있을 경우는 자동으로 시트에 적용됩니다."},
		{"DialogDocuments07","출력"},
		{"DialogDocuments08","닫기"},
		{"DialogDocuments09","설계서 출력"},
		{"DialogDocuments10","*선택해 주세요"},
		{"DialogDocuments11","개의 정의요소에 관해서 다음의 파일명으로 설계서가 출력됐습니다."},
		{"DialogDocuments12","개의 정의요소에 관해서는 시트가 출력되지 않았습니다. 같은 이름의 정의요소에 의한 시트명 중복일 수 있습니다."},
		{"DialogDocuments13","굴림체"},
		{"DialogDocuments14","돋움체"},
		{"DialogDocuments15","굴림"},
		{"DialogDocuments16","기능 설계서"},
		{"DialogDocuments17","서브 시스템명"},
		{"DialogDocuments18","기능명"},
		{"DialogDocuments19","기능종류"},
		{"DialogDocuments20","개요"},
		{"DialogDocuments21","매개변수"},
		{"DialogDocuments22","반환값"},
		{"DialogDocuments23","설명"},
		{"DialogDocuments24","입출력 리스트"},
		{"DialogDocuments25","입출력명"},
		{"DialogDocuments26","종류"},
		{"DialogDocuments27","패널"},
		{"DialogDocuments28","인쇄"},
		{"DialogDocuments29","페이지"},
		{"DialogDocuments30","이 기능이 이용하는 기능"},
		{"DialogDocuments31","기동 이벤트"},
		{"DialogDocuments32","이 기능을 이용하는 기능"},
		{"DialogDocuments33","이 기능을 직접 이용하는 업무"},
		{"DialogDocuments34","직무명"},
		{"DialogDocuments35","업무명"},
		{"DialogDocuments36","엑션"},
		{"DialogDocuments37","입출력 정의"},
		{"DialogDocuments38","입출력 종류"},
		{"DialogDocuments39","입출력 이미지"},
		{"DialogDocuments40a",""},
		{"DialogDocuments40b"," 을(를) 참조해 주세요"},
		{"DialogDocuments41","라벨"},
		{"DialogDocuments42","항목명"},
		{"DialogDocuments43","항목종류"},
		{"DialogDocuments44","옵션 입력항목"},
		{"DialogDocuments45","필수 입력항목"},
		{"DialogDocuments46","표시항목"},
		{"DialogDocuments47","GUI부품"},
		{"DialogDocuments48","필드"},
		{"DialogDocuments49","데이터종류"},
		{"DialogDocuments50","필드에 관한 조작"},
		{"DialogDocuments51","테이블 설계서"},
		{"DialogDocuments52","테이블명"},
		{"DialogDocuments53","테이블 종류"},
		{"DialogDocuments54","필드리스트"},
		{"DialogDocuments55","필드명"},
		{"DialogDocuments56","종류"},
		{"DialogDocuments57","생략값"},
		{"DialogDocuments58",""},
		{"DialogDocuments59","가능"},
		{"DialogDocuments60","키정의 리스트"},
		{"DialogDocuments61","키종류"},
		{"DialogDocuments62","필드구성"},
		{"DialogDocuments63","일차식별자"},
		{"DialogDocuments64","외부키"},
		{"DialogDocuments65","이차식별자"},
		{"DialogDocuments66","이용기능 리스트"},
		{"DialogDocuments67","키정의"},
		{"DialogDocuments68","관련명"},
		{"DialogDocuments69","관련테이블명"},
		{"DialogDocuments70","관련키정의"},
		{"DialogDocuments71","부모자식관계"},
		{"DialogDocuments72","참조관계"},
		{"DialogDocuments73","파생관계"},
		{"DialogDocuments74","Index" },
		{"DialogEditInstanceOnDatamodel1", "Edit Table Instances"},
		{"DialogEditInstanceOnDatamodel2", "Set Slide Number"},
		{"DialogEditInstanceOnDatamodel3", "Add Slide"},
		{"DialogEditInstanceOnDatamodel4", "Remove Slide"},
		{"DialogToListChangesOfFiles1", "Differences Between Files"},
		{"DialogToListChangesOfFiles2", "Differences between the current file and the target file will be listed. Push button to start."},
		{"DialogToListChangesOfFiles3", "Target File"},
		{"DialogToListChangesOfFiles4", "Target System"},
		{"DialogToListChangesOfFiles5", "Start"},
		{"DialogToListChangesOfFiles6", "Close"},
		{"DialogToListChangesOfFiles7", "No Changes"},
		{"DialogToListChangesOfFiles8", "Basic Information"},
		{"DialogToListChangesOfFiles9", "System"},
		{"DialogToListChangesOfFiles10", "Table"},
		{"DialogToListChangesOfFiles11", "Field"},
		{"DialogToListChangesOfFiles12", "Key"},
		{"DialogToListChangesOfFiles13", "Relationship"},
		{"DialogToListChangesOfFiles14", "Function"},
		{"DialogToListChangesOfFiles15", "Functions Called"},
		{"DialogToListChangesOfFiles16", "IO Panel"},
		{"DialogToListChangesOfFiles17", "IO WEB Pange"},
		{"DialogToListChangesOfFiles18", "IO Spool"},
		{"DialogToListChangesOfFiles19", "IO Table"},
		{"DialogToListChangesOfFiles20", "'s "},
		{"DialogToListChangesOfFiles21", " changed from '"},
		{"DialogToListChangesOfFiles22", "' into '"},
		{"DialogToListChangesOfFiles23", "'"},
		{"DialogToListChangesOfFiles24", "'s layout changed"},
		{"DialogToListChangesOfFiles25", "'s descriptions changed"},
		{"DialogToListChangesOfFiles26", "'s datamodel remarks changed"},
		{"DialogToListChangesOfFiles27", "'s name changed from '"},
		{"DialogToListChangesOfFiles28", "'"},
		{"DialogToListChangesOfFiles29", "'"},
		{"DialogToListChangesOfFiles30", " is added"},
		{"DialogToListChangesOfFiles31", " is deleted"},
		{"DialogToListChangesOfFiles32", "'s protocol changed"},
		{"DialogToListChangesOfFiles33", "'s datamodel changed"},
		{"DialogToListChangesOfFiles34", " is changed"},
		{"DialogToListChangesOfFiles35", " differences are found."},
		{"DialogReorganizeDataTypes01", "Reorganize Data Types" },
		{"DialogReorganizeDataTypes02", "Data Type From" },
		{"DialogReorganizeDataTypes03", "Data Type Into" },
		{"DialogReorganizeDataTypes04", "Close" },
		{"DialogReorganizeDataTypes05", "Transfer Fields Selected" },
		{"DialogReorganizeDataTypes06", "Delete Data Type From" },
		{"DialogScan01","문자열 검색/치환"},
		{"DialogScan02","검색문자열"},
		{"DialogScan03","치환문자열"},
		{"DialogScan04","대/소문자 구별"},
		{"DialogScan05","검색범위"},
		{"DialogScan06","시스템 설명"},
		{"DialogScan07","부문정의"},
		{"DialogScan08","테이블종류"},
		{"DialogScan09","데이터종류"},
		{"DialogScan10","기능종류"},
		{"DialogScan11","변경이력"},
		{"DialogScan12","업무플로우"},
		{"DialogScan13","직무정의"},
		{"DialogScan14","업무정의"},
		{"DialogScan15","서브시스템 설명"},
		{"DialogScan16","테이블정의"},
		{"DialogScan17","기능정의"},
		{"DialogScan18","검색시작"},
		{"DialogScan19","선"},
		{"DialogScan20","정의요소구분"},
		{"DialogScan21","정의요소명"},
		{"DialogScan22","속성명"},
		{"DialogScan23","속성값"},
		{"DialogScan24","Hit"},
		{"DialogScan25","닫기"},
		{"DialogScan26","담당업종류"},
		{"DialogScan28","선택행 모두바꾸기"},
		{"DialogScan29","리스트출력"},
		{"DialogScan30","(모든 직무)"},
		{"DialogScan31","(모든 서브시스템)"},
		{"DialogScan32","개의 정의요소의, "},
		{"DialogScan33","군데에서 지정하신 문자열이 발견되었습니다. 행을 선택하면 속성값이 표시됩니다."},
		{"DialogScan34","지정 문자열을 포함한 정의요소는 발견되지 않았습니다."},
		{"DialogScan35","시스템기술"},
		{"DialogScan36","부문정의"},
		{"DialogScan37","테이블종류"},
		{"DialogScan38","데이터종류"},
		{"DialogScan39","기능종류"},
		{"DialogScan40","변경이력"},
		{"DialogScan41","업무플로우"},
		{"DialogScan42","업무플로우/프로세스"},
		{"DialogScan43","업무플로우/플로우"},
		{"DialogScan44","직무정의"},
		{"DialogScan45","업무정의"},
		{"DialogScan46","업무정의/프로세스"},
		{"DialogScan47","업무정의/프로세스/UI"},
		{"DialogScan48","서브시스템기술"},
		{"DialogScan49","서브시스템기술/모델"},
		{"DialogScan50","테이블정의"},
		{"DialogScan51","테이블정의/필드"},
		{"DialogScan52","기능정의"},
		{"DialogScan53","기능정의/기동기능"},
		{"DialogScan54","기능정의/패널"},
		{"DialogScan55","기능정의/패널항목"},
		{"DialogScan56","기능정의/WEB페이지"},
		{"DialogScan57","기능정의/WEB페이지항목"},
		{"DialogScan58","기능정의/스풀"},
		{"DialogScan59","기능정의/스풀항목"},
		{"DialogScan60","기능정의/테이블"},
		{"DialogScan61","기능정의/테이블필드"},
		{"DialogScan62","ID"},
		{"DialogScan63","명칭"},
		{"DialogScan64","확장명"},
		{"DialogScan65","실행조건"},
		{"DialogScan66","라벨"},
		{"DialogScan67","인스턴스"},
		{"DialogScan68","이력명"},
		{"DialogScan69","설명"},
		{"DialogScan70","이벤트"},
		{"DialogScan71","별명"},
		{"DialogScan72","생략값"},
		{"DialogScan73","참조제약"},
		{"DialogScan74","기동이벤트"},
		{"DialogScan75","조작방법"},
		{"DialogScan76","개요"},
		{"DialogScan77","인수"},
		{"DialogScan78","반환값"},
		{"DialogScan79","입출력이미지"},
		{"DialogScan80","테이블관련"},
		{"DialogScan81","개의 정의요소의, "},
		{"DialogScan82","곳에서 지정문자열로 바뀌었습니다."},
		{"DialogScan83","데이터 모델설명" },
		{"DialogScan84","Terms and Rules" },
		{"DialogScan85","All Items" },
		{"DialogScan86","Synch-File" },
		{"DialogScan87","Doc.File" },
		{"DialogImportXEAD01","*.xead정의요소 불러오기"},
		{"DialogImportXEAD02","불러올 파일"},
		{"DialogImportXEAD03","불러올 시스템"},
		{"DialogImportXEAD04","대상정의요소"},
		{"DialogImportXEAD05","테이블정의와 기능정의"},
		{"DialogImportXEAD06","업무정의"},
		{"DialogImportXEAD07","불러오기"},
		{"DialogImportXEAD08","닫기"},
		{"DialogImportXEAD09","불러올 서브시스템"},
		{"DialogImportXEAD10","불러올 곳의  서브시스템"},
		{"DialogImportXEAD11","불러올 서브시스템에 포함된 테이블정의와 기능정의등이 불러올 곳의 서브시스템에 복사됩니다. ID(리스트순)로 대상이 식별되며, 내보낼 에 대상이 존재하면 갱신, 존재하지 않으면 신규추가됩니다. 따라서, 불러올 서브시스템에서도 불러올 곳의 서브시스템에서도  동종류정의 ID가 중복해서 존재할 경우, 예측할 수 없는 갱신이 발생할 수 있습니다.(처리후의 확인창에 [이름을 변경해서 저장]을 선택하실 것을 권장합니다). 그외에도 몇 가지 제약이 있으니 사전에 도움말을 확인해 주시기 바랍니다."},
		{"DialogImportXEAD12","(선택해 주세요)"},
		{"DialogImportXEAD13","불러올 직무"},
		{"DialogImportXEAD14","불러올 곳의 직무"},
		{"DialogImportXEAD15","불러올 직무에 포함되어 있는 업무정의가 내보낼 직무에 복사됩니다. ID(리스트순)로 대상이 식별되며, 내보낼 대상이 존재하면 갱신, 존재하지 않으면 신규추가됩니다. 따라서, 불러올 직무와 내보낼 직무에서도 업무정의 ID가 중복할 경우, 예측할 수 없는 갱신이 발생할 수 있습니다.(처리후의 확인창에 [이름을 변경해서 저장]을 선택하실 것을 권장합니다). 그외에도 몇가지의 제약이 있으니 도움말을 확인해 주시기 바랍니다."},
		{"DialogImportXEAD16","테이블정의로서, "},
		{"DialogImportXEAD17","개가 갱신되었고, "},
		{"DialogImportXEAD18","개가 추가되었고, "},
		{"DialogImportXEAD19","기능정의로서, "},
		{"DialogImportXEAD20","기능별 테이블 입출력 정의로서 특정되지 않은 테이블정의가 "},
		{"DialogImportXEAD21","개, "},
		{"DialogImportXEAD22","기동되는 기능으로서 특정되지 않은 기능정의가 "},
		{"DialogImportXEAD23","개 발견되었습니다."},
		{"DialogImportXEAD24","업무정의로서 "},
		{"DialogImportXEAD25","업무 프로세스내에서 사용되는 패널/스풀로 특정하지 못한 입출력정의가 "},
		{"DialogImportXEAD26","개 발견되었습니다."},
		{"DialogImportXEAD27","내보내기 존재하지 않는 키정의에 기반한 테이블 관련정의가 "},
		{"DialogImportXEAD28","개 발견되었고, 이것들은 불어오지 않았습니다."},
		{"DialogImportXEAD29","상세에 대해서는, "},
		{"DialogImportXEAD30","의 이름으로 출력된 로그파일을 확인하시기 바랍니다."},
		{"DialogImportXEAD31","불러올 곳의 파일"},
		{"DialogImportXEAD32","불러올 곳의 시스템"},
		{"DialogImportXEAD33","불러올 곳의 기존정의가 갱신되었습니다."},
		{"DialogImportXEAD34","불러올 곳의 신규정의로 추가되었습니다."},
		{"DialogImportXEAD35","이 관계하는 테이블 관련정의에 필요한 키정의 한쪽이 불러올 곳의 시스템에 발견되지 않았기 때문에 불러오지 않았습니다."},
		{"DialogImportXEAD36","이 관계하는 테이블관련정의가 불러올 곳에 신규추가 되었습니다."},
		{"DialogImportXEAD37","의 테이블정의가 불러올 곳에 존재하지 않기 때문에 상기 기능의 테이블 입출력정보로서 불러오지 않았습니다."},
		{"DialogImportXEAD38","의 기능정의가 불러올 곳에 존재하지 않기 때문에,"},
		{"DialogImportXEAD39","에서의 호출정보로서 임포트되지 않았습니다."},
		{"DialogImportXEAD40","의 패널/스풀정의가 불러올 곳에 존재하지 않기 때문에 상기 업무 패널/스풀 조작정보로서 불러오지 않았습니다. "},
		{"DialogImportXEAD41","(다른 이름으로 불러오기 결과가 저장되었을 가능성이 있습니다 )"},
		{"DialogImportXEAD42","이 외부테이블로서 서브시스템에서 이용되고 있지만, 그 정의내용이 불러올 곳의 시스템에 존재하지 않기 때문에 외부테이블의 이용에 관한 정보는 불러오지 않았습니다."},
		{"DialogImportXEAD43","테이블관련을 동반하고 있기 때문에 일차식별자의 필드구성의 변경은 반영되지 않았습니다. "},
		{"DialogImportXEAD44","기능정의"},
		{"DialogImportXEAD45","불러올 서브시스템에 포함되어 있는 기능정의가 불러올 곳의 서브시스템에 복사되었습니다. ID(리스트순)로 대상이 식별되서 불러올 곳에 대상이 존재하면 갱신, 존재하지 않으면 신규추가됩니다. 따라서 불러올 서브시스템에서도 불러올 곳의 서브시스템에서도 같은 종류로 정의된 ID가 중복할 경우, 예측할 수 없는 갱신이 발생할 수도 있습니다. (처리후에 나오는 확인창에서 [이름을 변경해서 저장]을 선택하실 것을 권장합니다). 이 외에도 몇가지의 제약이 있으니 도움말을 확인해 주시기 바랍니다."},
		{"DialogImportXEAD46","테이블정의"},
		{"DialogImportXEAD47","불러올 서브시스템에 포함되어 있는 테이블정의가 불러올 곳의 서브시스템에 복사되었습니다. ID(리스트순)로 대상이 식별되며 불러올에 대상이 존재하면 갱신, 존재하지 않으면 신규추가됩니다. 따라서 임포트 원서브시스템에서도 임포트 내보낼 서브시스템에서도 동종류정의의 ID가 중복해서 존재할 경우, 예측할 수 없는 갱신이 발생할 수도 있습니다. (처리후에 나오는 확인창에서 [이름을 변경해서 저장]을 선택하실 것을 권장합니다). 이 외에도 몇가지의 제약이 있으니 도움말을 확인해 주시기 바랍니다."},
		{"DialogImportXEAD48","불러오지 않았습니다. 불러올 곳에 대응하는 정의가 지정 서브시스템이외에 소속되어 있기 때문입니다."},
		{"DialogImportXEAD49","불러오지 않았습니다. 불러올 곳에 대응하는 정의가 지정 직무이외에 소속되어 있기 때문입니다."},
		{"DialogImportXEAD50","개가 불러오기 대상에서 제외되었습니다."},
		{"DialogImportXEAD51","If Data-flow has any process(task) that is not defined in target sysytem, importing will be canceled. Note that unexpected update may occur if ID of definitions are duplicated in the target. Reffer to HELP before you execute." },
		{"DialogImportXEAD52","Data-Flow to import" },
		{"DialogImportXEAD53","Target Data-Flow" },
		{"DialogImportXEAD54","Importing was canceled as a corresponding definition of task is missing in the target system." },
		{"DialogImportXEAD55","Importing Data-Flow succeeded." },
		{"DialogImportXEAD56","Importing Data-flow failed. " },
		{"DialogImportXEAD57","Importing was canceled as a corresponding definition of role is missing in the target system." },
		{"DialogImportSQL01","CreateTable문 불러오기"},
		{"DialogImportSQL02","불러올 파일"},
		{"DialogImportSQL03","불러오기 적용할 서브시스템"},
		{"DialogImportSQL04","R등록일시, ,R갱신일시, R등록유져, R갱신유져, 삭제플래그"},
		{"DialogImportSQL05","불러오기"},
		{"DialogImportSQL06","닫기"},
		{"DialogImportSQL07","(선택해 주세요)"},
		{"DialogImportSQL08","개의 테이블정의와 "},
		{"DialogImportSQL09","개의 테이블 관련정의등을 불러왔습니다."},
		{"DialogImportSQL10","데이터형에 기반해서 데이터종류를 설정한다"},
		{"DialogImportSQL11","이하의 명칭의 필드를 데이터모델상에 비표시로 한다"},
		{"DialogImportSQL12","테이블ID를 임포트순에 기반해서 자동설정한다"},
		{"DialogImportSQL13","문중의 필드명을 필드정의ID(Alias)로 간주한다"},
		{"DialogImportSQL14","문중의 필드코멘트를 필드정의명으로 간주한다"},
		{"DialogImportXEAF01","*.xeaf정의요소 불러오기"},
		{"DialogImportXEAF02","불러올 파일"},
		{"DialogImportXEAF03","불러올 시스템"},
		{"DialogImportXEAF04","Return Code" },
		{"DialogImportXEAF07","불러오기"},
		{"DialogImportXEAF08","닫기"},
		{"DialogImportXEAF09","불러올 서브시스템"},
		{"DialogImportXEAF10","불러올 곳의  서브시스템"},
		{"DialogImportXEAF11","Definitions of Tables and Functions of the selected subsystem will be imported into the target. Each of definitions are identified by their ID. Those definitions with ID which is already existing in the target will be skipped. Note that table-relationship will not be imported." },
		{"DialogImportXEAF12","(선택해 주세요)"},
		{"DialogImportXEAF13","Primary Table" },
		{"DialogImportXEAF14","Header Table" },
		{"DialogImportXEAF15","Detail Table" },
		{"DialogImportXEAF16","테이블정의로서, "},
		{"DialogImportXEAF17","개가 갱신되었고, "},
		{"DialogImportXEAF18","개가 추가되었고, "},
		{"DialogImportXEAF19","기능정의로서, "},
		{"DialogImportXEAF20","기능별 테이블 입출력 정의로서 특정되지 않은 테이블정의가 "},
		{"DialogImportXEAF21","개, "},
		{"DialogImportXEAF22","기동되는 기능으로서 특정되지 않은 기능정의가 "},
		{"DialogImportXEAF23","개 발견되었습니다."},
		{"DialogImportXEAF24","Batch Table" },
		{"DialogImportXEAF28","개 발견되었고, 이것들은 불어오지 않았습니다."},
		{"DialogImportXEAF29","상세에 대해서는, "},
		{"DialogImportXEAF30","의 이름으로 출력된 로그파일을 확인하시기 바랍니다."},
		{"DialogImportXEAF31","불러올 곳의 파일"},
		{"DialogImportXEAF32","불러올 곳의 시스템"},
		{"DialogImportXEAF34","불러올 곳의 신규정의로 추가되었습니다."},
		{"DialogImportXEAF37","의 테이블정의가 불러올 곳에 존재하지 않기 때문에 상기 기능의 테이블 입출력정보로서 불러오지 않았습니다."},
		{"DialogImportXEAF38","의 기능정의가 불러올 곳에 존재하지 않기 때문에,"},
		{"DialogImportXEAF41","(다른 이름으로 불러오기 결과가 저장되었을 가능성이 있습니다 )"},
		{"DialogImportXEAF44","기능정의"},
		{"DialogImportXEAF45","불러올 서브시스템에 포함되어 있는 기능정의가 불러올 곳의 서브시스템에 복사되었습니다. ID(리스트순)로 대상이 식별되서 불러올 곳에 대상이 존재하면 갱신, 존재하지 않으면 신규추가됩니다. 따라서 불러올 서브시스템에서도 불러올 곳의 서브시스템에서도 같은 종류로 정의된 ID가 중복할 경우, 예측할 수 없는 갱신이 발생할 수도 있습니다. (처리후에 나오는 확인창에서 [이름을 변경해서 저장]을 선택하실 것을 권장합니다). 이 외에도 몇가지의 제약이 있으니 도움말을 확인해 주시기 바랍니다."},
		{"DialogImportXEAF46","테이블정의"},
		{"DialogImportXEAF47","불러올 서브시스템에 포함되어 있는 테이블정의가 불러올 곳의 서브시스템에 복사되었습니다. ID(리스트순)로 대상이 식별되며 불러올에 대상이 존재하면 갱신, 존재하지 않으면 신규추가됩니다. 따라서 임포트 원서브시스템에서도 임포트 내보낼 서브시스템에서도 동종류정의의 ID가 중복해서 존재할 경우, 예측할 수 없는 갱신이 발생할 수도 있습니다. (처리후에 나오는 확인창에서 [이름을 변경해서 저장]을 선택하실 것을 권장합니다). 이 외에도 몇가지의 제약이 있으니 도움말을 확인해 주시기 바랍니다."},
		{"DialogImportXEAF48","불러오지 않았습니다. 불러올 곳에 대응하는 정의가 지정 서브시스템이외에 소속되어 있기 때문입니다."},
		{"DialogImportXEAF50","개가 불러오기 대상에서 제외되었습니다."},
		{"DialogTableSynchronize01","Synchronization of Table" },
		{"DialogTableSynchronize02","Close" },
		{"DialogTableSynchronize03","Import From Synch-File" },
		{"DialogTableSynchronize04","... Edit definitions or import them from Synch-File. Note that by importing you can not remove those 'extra' elements(fields and keys) in the target table." },
		{"DialogTableSynchronize05","Table definitions are synchronized now." },
		{"DialogTableSynchronize06","Unable to specify the table to be compared with as table id is blank." },
		{"DialogTableSynchronize07","Synch-File Name is invalid." },
		{"DialogTableSynchronize08","The table specified is not existing in Synch-File." },
		{"DialogTableSynchronize09",".Table name is different." },
		{"DialogTableSynchronize10",".Table description is different." },
		{"DialogTableSynchronize11",".Field(" },
		{"DialogTableSynchronize12",") has a different name." },
		{"DialogTableSynchronize13",") has a different data type." },
		{"DialogTableSynchronize14",") has a different description." },
		{"DialogTableSynchronize15",") does not exist in the table on Synch-File." },
		{"DialogTableSynchronize16",".Field(" },
		{"DialogTableSynchronize17",") defined in the table on Synch-File does not exist here." },
		{"DialogTableSynchronize18",".PK is different." },
		{"DialogTableSynchronize19",".Updating PK rejected as it has relationship(s)." },
		{"DialogTableSynchronize20",".Extra key definition exists here." },
		{"DialogTableSynchronize22",".Extra key definition exists in the table on Synch-File." },
		{"DialogTableSynchronize23","" },
		{"DialogTableSynchronize24"," difference(s) has been found:\n" },
		{"DialogTableSynchronize25","You can not refer to the table as it has an external refference already." },
		{"DialogTableSynchronize26",") has a different Attri-Type." },
		{"DialogTableSynchronize27",") has a different NotNull." },
		{"DialogTableSynchronize28",") has a different Default." },
		{"DialogTableSynchronize29",") has a different NoUpdate." },
		{"DialogTableSynchronize30",".Table alias is different." },
		{"DialogTableSynchronize31",".Table type is different." },
		{"S1","이 파일의 포멧버젼은  "},
		{"S2"," 입니다만, 이 버젼의 X-TEA Modeler가 취급할 수 있는 것은 "},
		{"S3"," 까지입니다. 최신의 X-TEA Modeler를 이용해 주시기 바랍니다. "},
		{"S5", "Launching X-TEA Modeler failed as Java version is " },
		{"S6", ". Required version is 1.7 - 1.8." },
		{"S7", "XEAF정의요소(*.xeaf)"},
		{"S10"," is newly registered." },
		{"S11"," is editted." },
		{"S12"," is deleted." },
		{"S49","시스템명"},
		{"S50","파일"},
		{"S51","신규"},
		{"S52","열기"},
		{"S53","종료"},
		{"S54","용지설정"},
		{"S55","인쇄"},
		{"S56","저장"},
		{"S57","다른이름으로 저장"},
		{"S58","편집"},
		{"S59","노드에 대한 변경취소"},
		{"S60","노드에 대한 변경을 다시실행"},
		{"S61","검색"},
		{"S62","문자열 검색/바꾸기"},
		{"S63","북마크 추가/삭제"},
		{"S64","불러오기"},
		{"S65","X-TEA정의요소(*.xead)"},
		{"S66","CreateTable문(*.sql;txt)"},
		{"S67","Recover Import Irregular" },
		{"S68","Close" },
		{"S69","Execute Recovery" },
		{"S70","Old import process might has resulted in irregulars.\nIt will recover them." },
		{"S71"," of irregulars found and recovered successfully." },
		{"S72", "No irregulars found to be recovered." },
		{"S73","북마크로 이동"},
		{"S74","Generate Matrics List" },
		{"S75","Subject area * Task" },
		{"S76","Subject area * Function" },
		{"S77","Task * Function" },
		{"S78","Task * Table" },
		{"S79","Table * Function" },
		{"S80","v" },
		{"S81","Matrix List is generated with the name as -" },
		{"S82","설계서출력"},
		{"S83","도구"},
		{"S84","업무 리스트출력"},
		{"S85","테이블 리스트출력"},
		{"S86","기능 리스트출력"},
		{"S87","Edit DDL Settings"},
		{"S88","Reorganize Data Types" },
		{"S89","지정URL로 이동"},
		{"S90","도움말"},
		{"S91","개요와 목차"},
		{"S92","버젼정보"},
		{"S93","Generate DDL List" },
		{"S94","파일(F)"},
		{"S95","편집(E)"},
		{"S96","검색(S)"},
		{"S97","도구(T)"},
		{"S98","도움말(H)"},
		{"S99","필드리스트 출력"},
		{"S100","하위요소를 추가"},
		{"S101","리스트형식으로 추가"},
		{"S102","하위요소 붙여넣기"},
		{"S103","복사"},
		{"S104","잘라내기"},
		{"S105","삭제"},
		{"S106","하위요소를 추가"},
		{"S107","패널"},
		{"S108","스풀"},
		{"S109","WEB페이지"},
		{"S110","외부키"},
		{"S111","이차식별자"},
		{"S112","Index" },
		{"S120","List Changes" },
		{"S121","Select The File to compare with." },
		{"S122","Noted Item List" },
		{"S133","양식의 사이즈를 변경한다"},
		{"S137","폼의 배경색을 변경"},
		{"S150","선택영역의 배경색을 변경"},
		{"S163","선택영역의 문자색을 변경"},
		{"S176","실행 취소"},
		{"S177","다시 실행"},
		{"S178","잘라내기"},
		{"S179","복사"},
		{"S180","붙여넣기"},
		{"S181","삭제"},
		{"S182","모두선택"},
		{"S183","선택영역의 문자에 하선을 긋는다"},
		{"S184","선택영역의 서식을 초기화"},
		{"S185","이미지출력"},
		{"S186","선택영역의 하선을 지운다"},
		{"S187","직사각형 선택"},
		{"S189","시스템명"},
		{"S190","이미지파일탐색"},
		{"S192","버젼"},
		{"S193","Referring Files" },
		{"S195","시스템 설명"},
		{"S196","부문리스트"},
		{"S198","부문명"},
		{"S201","ID(Seq.)"},
		{"S204","설명"},
		{"S206","테이블종류리스트"},
		{"S208","테이블종류명"},
		{"S209","담당업종류리스트"},
		{"S210","담당업종류명"},
		{"S216","데이터종류리스트"},
		{"S218","데이터종류명"},
		{"S223","SQL표현"},
		{"S227","기본데이터형"},
		{"S237","자리수"},
		{"S240","소수자리"},
		{"S242","기능종류리스트"},
		{"S244","기능종류명"},
		{"S245", "Terms and Rules" },
		{"S246", "Headding" },
		{"S247", "Definitions" },
		{"S248", "ID" },
		{"S249", "HTML File" },
		{"S252","보수이력"},
		{"S254","버젼등"},
		{"S257","판바꿈일자(리스트순)"},
		{"S260","변경내용"},
		{"S265","부문명"},
		{"S271","관련담당명"},
		{"S277","테이블종류명"},
		{"S283","관련테이블명"},
		{"S284","소속 서브시스템명"},
		{"S289","데이터종류명"},
		{"S290","기본 데이터형"},
		{"S291","자리수"},
		{"S292","소수자리"},
		{"S293","SQL표현"},
		{"S297","ID(alias)"},
		{"S298","관련필드명"},
		{"S299","소속테이블명"},
		{"S300","소속서브시스템명"},
		{"S305","기능종류명"},
		{"S311","관련기능명"},
		{"S312","소속서브시스템명"},
		{"S313","인수"},
		{"S317","판바꿈일자"},
		{"S318","버젼등"},
		{"S319","변경내용"},
		{"S324","업무플로우명"},
		{"S339","직무정의"},
		{"S340","직무명"},
		{"S341","부문"},
		{"S342", "Tsk" },
		{"S348","직무명"},
		{"S356","부문"},
		{"S359","업무정의"},
		{"S360","담당업무명"},
		{"S361","이벤트"},
		{"S362","담당업종류"},
		{"S363","업무명"},
		{"S368","이 업무가 시작되어야 할 [상황]을 나타냅니다"},
		{"S372","담당업무명"},
		{"S375","프로토콜"},
		{"S380","관련 업무플로우"},
		{"S390","주석"},
		{"S391","실행조건"},
		{"S392","필요하다면 이 엑션이 "+"\n"+"실행되어야 할 조건을 지정해 주시기 바랍니다"},
		{"S394","엑션"},
		{"S400","조작방법"},
		{"S403","입출력이미지 설명"},
		{"S407","서브시스템리스트"},
		{"S408","기능계층 뷰"},
		{"S411","기동 이벤트"},
		{"S413","서브시스템"},
		{"S415","기능명"},
		{"S417","기능종류"},
		{"S419","개요"},
		{"S421","인수/반환값"},
		{"S434","Synch-Sts" },
		{"S435","Model File" },
		{"S436","서브시스템명"},
		{"S437","표"},
		{"S438","기"},
		{"S439","외C"},
		{"S440","외R"},
		{"S441","외U"},
		{"S442","외D"},
		{"S443","외기"},
		{"S448","테이블ID"},
		{"S449","테이블 입출력명"},
		{"S464","테이블 리스트"},
		{"S465","외부테이블 리스트"},
		{"S466","데이터 모델"},
		{"S467","데이터 모델설명" },
		{"S471","테이블명"},
		{"S472","모델"},
		{"S473","Alias" },
		{"S477","테이블 종류"},
		{"S478","일차 식별자"},
		{"S479","외C"},
		{"S480","외R"},
		{"S481","외U"},
		{"S482","외D"},
		{"S483","표시"},
		{"S490","모델"},
		{"S495","테이블종류"},
		{"S496","일차 식별자"},
		{"S502","종류"},
		{"S508","일차 식별자"},
		{"S510","Referred File"},
		{"S511","Synch-Check"},
		{"S518","CREATE문"},
		{"S519","내부이용 기능리스트"},
		{"S520","외부이용 기능리스트"},
		{"S521","Referring Files" },
		{"S523","기능명"},
		{"S532","기능명"},
		{"S540","리스트순"},
		{"S542","필드명"},
		{"S543","속성구분"},
		{"S544","데이터종류"},
		{"S546","생략값"},
		{"S547","모델"},
		{"S550","신규"},
		{"S554","속성구분"},
		{"S556","종류"},
		{"S558","고유속성"},
		{"S559","통상의 속성항목인것을 나타냅니다"},
		{"S561","계승속성"},
		{"S562","부모테이블, 또는 참조할 테이블상의 항목과 연동하고 있음을 나타냅니다"},
		{"S564","도출속성"},
		{"S565","타항목을 조합해서 산출되는 항목임을 나타냅니다"},
		{"S569","생략값"},
		{"S577","필드명"},
		{"S581","UPD" },
		{"S582","No Update" },
		{"S583","모델표시"},
		{"S585","이것을 체크하시면 데이터모델의 엔티티상자내에서 이 필드가 표시됩니다"},
		{"S586","(설명없음)"},
		{"S592","기능명"},
		{"S597","항목에 대한 조작"},
		{"S602","기능명"},
		{"S607","항목에 대한 조작"},
		{"S612","종류"},
		{"S613","필드구성"},
		{"S616","KEY종류"},
		{"S624","테이블관련리스트"},
		{"S632","기능리스트"},
		{"S633","외부기능리스트"},
		{"S638","기능명"},
		{"S639","기능종류"},
		{"S640","개요"},
		{"S641","인수"},
		{"S642","반환값"},
		{"S643","Function Called" },
		{"S644","Summary" },
		{"S645","Table Operation" },
		{"S646","Table Remarks" },
		{"S647","기능ID"},
		{"S648","기능명"},
		{"S649","기능종류"},
		{"S650","개요"},
		{"S662","종류"},
		{"S664","기능명"},
		{"S666","인수/반환값"},
		{"S667","Doc.File" },
		{"S668","개요"},
		{"S669","<CURRENT> is the folder of this content file. Use ';' to separate values." },
		{"S673","입출력리스트"},
		{"S674","이 기능이 이용하는 기능"},
		{"S675","이 기능을 이용하는 기능"},
		{"S676","이 기능을 직접이용하는 업무"},
		{"S680","입출력명"},
		{"S688","기능명"},
		{"S689","기동이벤트"},
		{"S693","입출력명"},
		{"S694","담당명"},
		{"S696","업무명"},
		{"S697","엑션"},
		{"S701"," 패널이미지"},
		{"S703","패널명"},
		{"S717","스풀명"},
		{"S727"," 스풀이미지"},
		{"S739","일차 식별자"},
		{"S742","입출력 접미사명"},
		{"S745","조작구분"},
		{"S750", "Position" },
		{"S751", "Primary Table" },
		{"S752", "Header Table" },
		{"S753", "Detail Table" },
		{"S754", "Join Table" },
		{"S755", "Others" },
		{"S761","테이블정의에 점프"},
		{"S766"," 페이지이미지"},
		{"S768","페이지명"},
		{"S774","파일명"},
		{"S783","종료"},
		{"S782","파일을 신규작성해서 열기"},
		{"S781","파일을 선택해서 열기"},
		{"S784","열람/편집되는 파일의 지정에 관해서, 아래에서 선택해 주세요."},
		{"S785","X-TEA Modeler - 편집파일 선택"},
		{"S786","기존 컨텐츠 파일열기"},
		{"S789","신규작성해서 열기"},
		{"S788","X-TEA Modeler - 폴더와 파일명(한문불가)을 지정해 주세요."},
		{"S794","지정된 xead파일의 해석에 실패했습니다. 양식을 확인해 주세요"},
		{"S798","유효한 확장자를 갖는 지정명의 파일을 찾을 수 없습니다."},
		{"S799","지정파일의 확장자가 유효하지 않습니다."},
		{"S800","This action has sub-actions.　Copy them?" },
		{"S801","Copy Option of Task-Action" },
		{"S806","취소"},
		{"S805","파일명 재지정"},
		{"S804","저장"},
		{"S807","지정된 파일은 이미 있습니다. 저장하시겠습니까?"},
		{"S808","X-TEA Modeler - 편집파일 선택"},
		{"S811","지정된 파일은 읽기전용입니다. Modeler에서 편집"},
		{"S813","해도, 그 내용을 반영할 수 없는 점에 주의해 주세요."},
		{"S860","추가"},
		{"S861","추가(패널)"},
		{"S862","추가(스풀)"},
		{"S863","추가(WEB페이지)"},
		{"S864","추가(외부키)"},
		{"S865","추가(이차식별자)"},
		{"S866","복사"},
		{"S867","붙여넣기"},
		{"S868","삭제"},
		{"S869","빼기"},
		{"S870","이동↑"},
		{"S871","이동↓"},
		{"S872","이동←"},
		{"S873","이동→"},
		{"S874","점프"},
		{"S875","슬라이드쇼"},
		{"S876","슬라이드순서"},
		{"S877","테이블 정렬"},
		{"S878","이미지출력"},
		{"S879","편집 힌트"},
		{"S880","리스트출력"},
		{"S881","재임포트"},
		{"S882","Appearance" },
		{"S883","추가(Index)" },
		{"S884","Change A/D" },
		{"S885","Show Instance" },
		{"S900","No instance registered for tables." },
		{"S915","노드 추가"},
		{"S916","노드 붙여넣기"},
		{"S919","조작방법"},
		{"S993","키는 무엇인가"},
		{"S1000","X-TEA Modeler - 바꾸기 결과의 저장확인"},
		{"S1001","바꾸기 처리의 결과를 저장하시겠습니까?"},
		{"S1002","현재의 파일내용이 변경되었습니다. 검색/바꾸기 전에 저장해야 합니다."},
		{"S1098","저장하고 종료"},
		{"S1099","저장하지 않고 종료"},
		{"S1100","편집으로 돌아가기"},
		{"S1101","편집결과를 저장하고 종료하시겠습니까?"},
		{"S1102","X-TEA Modeler - 변경내용 저장"},
		{"S1104","저장하지 않고 신규작성"},
		{"S1103","저장후에 신규작성"},
		{"S1105","X-TEA Modeler - Save Recovery" },
		{"S1106","편집결과를 저장한 후에 신규작성하시겠습니까?"},
		{"S1107","X-TEA Modeler - 신규작성에 따른 변경의 저장"},
		{"S1108","X-TEA Modeler - 임포트결과 저장"},
		{"S1109","신규작성해서 열기"},
		{"S1110","임포트결과를 저장하시겠습니까?"},
		{"S1111","저장하기"},
		{"S1112","이름을 변경해서 저장"},
		{"S1113","저장안함"},
		{"S1114","저장한 후 열기"},
		{"S1115","저장하지 않고 열기"},
		{"S1116","현재의 파일내용이 변경되었습니다. 임포트 전에 저장하실 필요가 있습니다."},
		{"S1117","현재의 파일내용이 변경되었습니다. 저장한 후에 여시겠습니까?"},
		{"S1118","변경내용의 저장"},
		{"S1119","기존의 xead파일열기"},
		{"S1120","원임포트가 되는 xead파일열기"},
		{"S1121","CreateTable문을 포함한 텍스트(txt;sql)열기"},
		{"S1122","X-TEA Modeler - Save Synchronization"},
		{"S1123","Do you save changes?"},
		{"S1125","이 이름으로 저장"},
		{"S1126","Current content has been changed. You need to save before Reporting." },
		{"S1149","저장하지 못했습니다."},
		{"S1150","This file has been already updated by the other user. Save changes?" },
		{"S1151","Backup File" },
		{"S1152","Do you backup current file before saving?" },
		{"S1225","№,직무ID,직무명,소속부문,업무ID,업무명,이벤트,담당업종류ID,담당업종류명"},
		{"S1242","X-TEA Modeler - 업무리스트의 폴더와 CSV파일명을 지정해 주세요."},
		{"S1247","출력되어야 할 업무정의가 존재하지 않습니다"},
		{"S1250","№,서브시스템ID,서브시스템명,테이블ID,Synch-File Name,테이블명,C,R,U,D,테이블종류,일차 식별자,FLD,외C,외R,외U,외D"},
		{"S1251","№,서브시스템ID,서브시스템명,테이블ID,테이블명,Key,필드ID,필드명,속성,데이터종류,Null,UPD,생략값,모델,설명"},
		{"S1310","X-TEA Modeler - 테이블리스트 폴더와 CSV파일명을 지정해 주세요."},
		{"S1315","출력될 테이블정의가 존재하지 않습니다"},
		{"S1317","No noted item exists. Noted items are those contain keyword '@NOTE@'\nin remarks. They are indicated with * in the tree view." },
		{"S1318","No.,Item Type,Item Name" },
		{"S1319","№,서브시스템ID,서브시스템명,기능ID,기능명,종류,개요, 이 기능을 직접 이용하는 업무"},
		{"S1347",") ]"},
		{"S1343","["},
		{"S1348","등"},
		{"S1350","없음"},
		{"S1353","X-TEA Modeler - 기능리스트 폴더와 CSV파일명을 지정해 주세요."},
		{"S1358","출력되어야 할 기능정의가 존재하지 않습니다"},
		{"S1360","X-TEA Modeler - CREATE문을 저장할 폴더와 txt파일명을 지정해 주세요."},
		{"S1366","경고:키항목의 데이터종류설정에 부정합성이 발견되었습니다. FOREIGN KEY 스테이트먼트 상의 "},
		{"S1368","항목명에 (?)로 표시되어 있는 부분에 관해서 , 관련하는 키정의 간의  데이터종류구성을 조사하시기 바랍니다."},
		{"S1370","자세한 내용은 도움말의 키정의에 관한 설명을 참조해 주세요"},
		{"S1371","출력되어야 할 테이블정의가 존재하지 않습니다"},
		{"S1372","다음 파일명으로 설명문이 출력되었습니다."},
		{"S1582","X-TEA Modeler - 업무프로토콜 데이터를 저장할 폴더와 csv파일명을 지정해 주세요."},
		{"S1587","담당자,"},
		{"S1593","업무,"},
		{"S1599","이벤트,"},
		{"S1600",", "},
		{"S1613","처리되어야 할 업무정의가 존재하지 않습니다"},
		{"S1617"," 가 무효합니다"},
		{"S1618","커서지정되어 있는 문자열"},
		{"S1621","은 URL로서 무효합니다. ”http:”나 ”file:”로 시작되어, 반각콤마”,”, 세미콜론”;”, 닫는 괄호”)”"},
		{"S1623","또는 행말에 끝나는 문자열이어야 합니다."},
		{"S1629","이 발견되지 않습니다."},
		{"S1628","도움말파일"},
		{"S1735","기존의 CSV파일열기"},
		{"S1747","양식에 따른 유효한 행이 발견되지 않습니다. 도움말에서 양식을 다시 확인해 주세요"},
		{"S1748","일부의 행은 적용되지 않았습니다. 도움말에서 양식을 다시 확인해 주세요"},
		{"S1749","ID was updated as the definition was specified by name value." },
		{"S1770","패널의 넓이와 높이를 순서대로, 반각자리수"},
		{"S1772","로 지정해 주세요.양식의 우변아나 하변"},
		{"S1774","을 마우스로 드래그해도 사이즈의 변경이 가능합니다."},
		{"S1779","스풀의 넓이와 높이를 문자수로 지정해 주세요.(넓이,높이)"},
		{"S1797","(기능계층의 루트)"},
		{"S1829","입출력정의 [파일명]이 올바르지 않습니다."},
		{"S1845","테이블입출력"},
		{"S1846","업무플로우["},
		{"S1847","](Page "},
		{"S1848","데이터 모델["},
		{"S1920","경고:이 필드를 포함한 키정의가 이미 테이블관련을 포함하고 있습니다. 관련정의에 있어서, "},
		{"S1922","이미 한편의 키정의 데이터종류 구성과 모순이 발생할 수 있음에 주의해 주세요. 모순이 있는 "},
		{"S1924","경우는 테이블정의의 [CREATE TABLE문]상에서 경고멧세지가 표시됩니다. "},
		{"S1959","X-TEA Modeler - 리스트데이터를 저장할 폴더와 CSV파일명을 지정해 주세요."},
		{"S1976","[파일명]을 올바르게 설정한 후에 , 오른쪽 클릭으로 표시되는 [다시 불러오기]를 실행해 주세요"},
		{"S1977", "You can not edit items on this list. These" },
		{"S1978", "are listed according to definition of tasks" },
		{"S1979", "which you can edit as required." },
		{"S1981","이 리스트는 이곳에서 편집되는 것이 아니라, [직무정의]의 편집내용에 따라서 "},
		{"S1983","표시전용으로 조회되는 것입니다. 필요하다면 [직무정의]의 [소속부문]"},
		{"S1985","을 편집해 주세요. 이 리스트의 내용도 자동으로 변경됩니다. "},
		{"S1987","이 리스트는 이곳에서 편집되는 것이 아니라, [테이블정의]의 편집내용에 따라서 "},
		{"S1989","표시전용으로 조회되는 것입니다. 필요하다면 [테이블정의]의 [테이블종류]"},
		{"S1991","를 편집해 주세요. 이 리스트의 내용도 자동으로 변경됩니다. "},
		{"S1993","이 리스트는 이곳에서 편집되는 것이 아니라, [필드정의]의 편집내용에 따라서 "},
		{"S1995","표시전용으로 조회되는 것입니다. 필요하다면 [필드정의]의 [데이터종류]"},
		{"S1997","를 편집해 주세요. 이 리스트의 내용도 자동으로 변경됩니다. "},
		{"S1999","이 리스트는 이곳에서 편집되는 것이 아니라, [기능정의]의 편집내용에 따라서 "},
		{"S2001","표시전용으로 조회되는 것입니다. 필요하다면 [기능정의]의 [기능종류]"},
		{"S2003","을 편집해 주세요. 이 리스트의 내용도 자동으로 변경됩니다. "},
		{"S2005","업무플로우에서는 여러가지 등장할 수 있습니다만, 크게 [시스템경계], [프로세스 노드], [플로우], "},
		{"S2007","[스트레이지 노드]의 4종류로 나눌수 있습니다. [시스템경계(배경에 있는 흰색 틀)]의 틀 부분을 "},
		{"S2009","드래그하면 크기나 위치를 변경할 수 있습니다. [프로세스 노드(파란색의 타원)]를 추가하려면, 트리"},
		{"S2011","뷰상의 [직무별 담당업무]→[직무정의]→[업무정의]의 노드를 이곳에 드래그&드롭"},
		{"S2013","해 주세요[프로세스 노드]의 명칭부분에서 오른쪽클릭을 하시면 [플로우(화살표)]를 추가하기 위한 "},
		{"S2015","항목이 나타납니다. [스트레이지 노드(그 외의 여러가지 아이콘)]를 추가하고 싶은 경우는 아무것도 "},
		{"S2017","없는 곳에서 오른쪽 클릭을 하면 나타나는 메뉴항목[노드 추가]을 이용하시기 바랍니다. "},
		{"S2019","화살표키(Tab키가 아닙니다)의 [→]로 페이지가 바뀌며, [←]로 리턴됩니다. "},
		{"S2021","Shift키를 누르면서 화살표키를 누르면, 선두나 마지막 페이지에 이동합니다. "},
		{"S2023","도중에 종료하고 싶을 경우는 Esc키를 누르세요. "},
		{"S2025","트리뷰위에서 다른 직무아래의 [업무정의]노드를 여기에 드래그&드롭"},
		{"S2027","하면 이쪽으로 이동합니다. "},
//		{"S2029","입출력 이미지를 이곳에서 편집하실 수 없습니다. 이것들은 레이아웃을 편집하기 위해서는, 메인트리뷰"},
//		{"S2031","상의 [서버모듈]→[서브시스템정의]→[기능구성]→[기능정의]→[입출력정의"},
//		{"S2033","(패널/스풀)]노드를 열어 주시기 바랍니다([점프]에서 간단히 액세스가능합니다). 이 종류의 "},
//		{"S2035","노드를 이곳에 드래그&드롭하면 이 엑션에서 이용되는 입출력정의로서 추가됩니다. "},
//		{"S2037","또한 Modeler상에서는 [WEB페이지] 레이아웃을 편집할 수 없는 점에 주의해 주세요"},
		{"S2029","You can not edit IO image here. You need to open the pane of treeview node" },
		{"S2031","which is located under node of function. You can easily access to the pane" },
		{"S2033","by selecting item of \'Jump\' on popup menu. In order to add IO image for the" },
		{"S2035","action, drag-and-drop these nodes into here(use shift key to replace)." },
		{"S2037","Note that X-TEA Modeler has no function to edit WEB page(HTML file)." },
		{"S2039","IO images related to the action are defined as treeview nodes(Panel/Spool/" },
		{"S2041","Web-page/IO Table/Function) which located under function definitions. In" },
		{"S2043","order to add IO image for the action, drag-and-drop these nodes into here." },
		{"S2044","With Shift-key down, IO image will be replaced." },
		{"S2045","이 트리구조는, 매번의 기능정의의 [이 기능이 이용하는 기능]의 내용에 "},
		{"S2047","따라서 표시되고 있는 것으로 이곳에서는 편집할 수 없습니다."},
		{"S2049","입출력이미지를 이곳에서는 편집할 수 없습니다. 이것들은 레이아웃을 편집하시려면, 메인"},
		{"S2051","트리뷰상의 [서버모듈]→[서브시스템정의]→[기능구성]→[기능정의]"},
		{"S2053","→[입출력정의(패널/스풀)]の노드를 열어주시기 바랍니다. ([점프]로 간단히 악세스"},
		{"S2055","가능합니다). 또한, [WEB페이지]의 레이아웃에 관해서는 Modeler상에서 편집할 수는 없습니다. "},
		{"S2057","트리뷰상의 타 서브시스템하의 [테이블정의]노드를 이곳으로 드래그&드롭"},
		{"S2059","하시면 이쪽으로 이동합니다. 이 때에, 이동 원서브시스템에서는 그 테이블가"},
		{"S2061","[외부테이블리스트]상에 남는 점에 주의해 주세요"},
		{"S2063","트리뷰상의 타서브시스템하의 [테이블정의]노드를 이곳에 드래그&드롭"},
		{"S2065","하시면 그 테이블이 이 서브시스템의 [외부테이블]로서 등록됩니다. 외부테이블"},
		{"S2067","에 대한 갱신조작(CRUD중에 C,U,D)을 가능하면 피하는 것이, 서브시스템의 독립성"},
		{"S2069","과 시스템 전체의 보수성을 높이는 비결입니다."},
		{ "S2071", "By drag&dropping treeview node of <table> into this area," },
		{ "S2073", "it will appear as a entity box on the datamodel. You can" },
		{ "S2075", "add a relationship lines by drag&dropping key-field in" },
		{ "S2077", "entity-box into table name area. You can also hide relation-" },
		{ "S2079", "ship lines. Reffer to HELP." },
		{"S2081","이 리스트는 이곳에서 편집되는 것이 아니라, 이 서브시스템에 포함되어 있는 [기능정의]의 "},
		{"S2083","편집내용에 따라서 표시전용으로 조회되는 것입니다. 필요하다면 [기능정의]의 "},
		{"S2085","[테이블IO]를 편집해 주세요. 이 리스트의 내용도 자동으로 변경됩니다. "},
		{"S2086","This is a list of model files which refer to the" },
		{"S2087","definition of table. Candidates of files should be" },
		{"S2088","registered on Referring Files of System node." },
		{"S2093","트리뷰상의 [필드정의]노드를 이곳에 드래그&드롭하시면, "},
		{"S2095","정의내용이 복사되며 추가됩니다. 이 조작은 이것들의 노드를 [복사]"},
		{"S2097","해서 [붙여넣기]를 하는 것보다 편리합니다. 필드의 정렬순서으로 변경하실 경우는 "},
		{"S2098","은, 이 리스트상에서 행을 상하로 드래그해 주세요"},
		{"S2111","테이블에는 반드시 [일차 식별자]가 한개만 포함됩니다. 테이블을 신규추가하시면 "},
		{"S2113","일차 식별자가 자동적으로 추가되기 때문에, 새롭게 추가가능한 것은 [이차식별자]나 "},
		{"S2115","[외부키]중 하나입니다. [일차 식별자]나 [이차식별자]의 실제값은 테이블내"},
		{"S2117","에서 중복하는 일이 없고, [외부키]의 실제값은 관련하는 테이블상에 존재하는 값"},
		{"S2119","만이 됩니다. 자세한 내용에 관해서는 메뉴얼에서 확인해 주세요"},
		{"S2121","트리뷰상의, 이 테이블에 포함되는 [필드정의]노드를 이곳에 "},
		{"S2123","드래그&드롭하시면 , 키항목으로 추가됩니다. 다른 테이블에"},
		{"S2125","포함되는 필드를 드래그&드롭하는 것은 유효하지 않습니다. 키항목의 정렬순서"},
		{"S2126","를 변경하고 싶을 경우에는 이 리스트상에서 행을 상하로 드래그해 주세요"},
		{"S2127","트리뷰상의 다른 [키정의]노드를 이곳에 드래그&드롭하시면, "},
		{"S2129","새로운 [테이블관련]이 생성됩니다. 단, 어떠한 키를 정의해도 좋다"},
		{"S2131","라고는 할 수 없습니다. 키에 포함되는 필드구성에 관해서는 몇가지의 "},
		{"S2133","제약이 있습니다. 자세한 내용에 관해서는 메뉴얼에서 확인해 주세요"},
		{"S2135","트리뷰상의 다른 서브시스템하의 [기능정의]의 노드를 이곳에 "},
		{"S2137","드래그&드롭하시면 , 이쪽으로 이동합니다. "},
		{"S2139","이 리스트는 이곳에서 편집되는 것이 아니라, 이 서브시스템에 포함되는 [기능정의]가 이용하고 "},
		{"S2141","있는 기능중, 다른 서브시스템에 포함되는 것을 표시전용으로서 조회한 것입니다. 필요하다면 "},
		{"S2143","[기능정의]의 내용을 편집해 주세요. 이 리스트의 내용도 자동으로 변경됩니다. "},
		{"S2145","트리뷰상의 [테이블정의]노드를 이곳에 드래그&드롭"},
		{"S2147","하시면, 그 테이블에 기반하는 새로운 입출력정의가 추가됩니다. "},
		{"S2149","또, [패널정의], [스풀정의], [테이블 입출력]노드를 이곳에 "},
		{"S2151","드래그&드롭하시면 , 정의내용이 복사되어 추가됩니다. 이 "},
		{"S2153","조작은 그것들의 노드를 [복사]해서 [붙여넣기]하는 것보다 편리합니다. "},
		{"S2155","페이지의 내용은 X-TEA Modeler에서는 편집하실 수 없습니다. 외부 에디터를 이용해 주세요."},
		{"S2157","트리뷰상의 , [기능정의]노드를 이곳에 드래그&드롭하시면 , "},
		{"S2159","이 기능이 이용하는 기능으로 추가됩니다. 기능의 정렬순서를 변경하고 싶을 "},
		{"S2160","경우에는, 이 리스트상에서 행을 상하로 드래그해 주세요"},
		{"S2161","이 리스트는 이곳에서 편집되는 것이 아니라, 다른 [기능정의]의 편집내용에 따라서 "},
		{"S2163","표시전용으로 조회되는 것입니다. 필요하다면 , 관련하는 [기능정의]내용을 "},
		{"S2165","편집해 주세요. 이 리스트도 자동적으로 변경됩니다. "},
		{"S2167","이 리스트는 이곳에서 편집되는 것이 아니라, [업무정의]の편집내용에 따라서 "},
		{"S2169","표시전용으로 조회되는 것입니다. 필요하다면 , 관련하는 [업무정의]의 "},
		{"S2171","내용을 편집해 주세요. 이 리스트도 자동으로 변경됩니다. "},
		{"S2173","리스트상의 행은 여기서 추가/삭제하실 수 없습니다. 그것들은 [테이블정의]의 편집내용"},
		{"S2175","에 상응해서 자동으로 설정되기 때문입니다. 필요하다면 , 관련하는 [테이블정의]의 "},
		{"S2177","내용을 편집해 주세요. 이 리스트도 자동으로 변경됩니다. "},
		{"S2184","신규부문"},
		{"S2185","신규담당업종류"},
		{"S2198","신규테이블종류"},
		{"S2212","신규데이터종류"},
		{"S2235","신규기능종류"},
		{"S2236", "New Terms and Rules" },
		{"S2274","신규노드"},
		{"S2286",". . . 이라면"},
		{"S2288",". . . 을. . . 한다"},
		{"S2300","CDGogeak,7,고객코드"},
		{"S2301","처럼, 신규데이터종류의 ID(리스트정렬)와 자리수와 명칭을 "},
		{"S2302","콤마로 연결해서 지정해 주세요.지정길이의 문자형 항목"},
		{"S2303","으로서 데이터종류 정의가 신규작성됩니다. 정의상의 다른 "},
		{"S2304","속성에 관해서는 [시스템정의/데이터종류리스트]페이지"},
		{"S2305","에서 별도 설정해 주세요"},
		{"S2527","이 테이블은 다른 기능에서 이용되고 있기 때문에 제거할 수 없습니다. "},
		{"S2536","관련정의를 포함한 키이기 때문에, 데이터 항목을 제거할 수 없습니다. "},
		{"S2539","이 부문에 소속하는 담당자가 존재하기 때문에  삭제할 수 없습니다. "},
		{"S2540","최소한 1건의 부문정의가 필요하기 때문에 삭제할 수 없습니다. "},
		{"S2542","이 종류가 지정된 테이블가 존재하고 있기 때문에 삭제할 수 없습니다. "},
		{"S2543","최소한 1건의 종류정의가 필요하기 때문에 삭제할 수 없습니다. "},
		{"S2545","이 종류가 지정된 데이터항목이 존재하고 있기 때문에 삭제할 수 없습니다. "},
		{"S2548","이 종류가 지정된 기능이 존재하고 있기 때문에,  삭제할 수 없습니다. "},
		{"S2551","최소한 1건의 보수이력이 필요하기 때문에 삭제할 수 없습니다. "},
		{"S2593","기점이 되는 엑션은 삭제할 수 없습니다. "},
		{"S2612","화상파일의 형식을 선택해 주세요.            "},
		{"S2613","X-TEA Modeler - 화상파일형식 선택"},
		{"S2617","형식)을지정해 주세요."},
		{"S2616","X-TEA Modeler - 이미지파일명("},
		//{"S2623","인쇄용 배색"},
		//{"S2622","통상 배색"},
		{"S2624","업무플로우の배색설정을 선택해 주세요. "},
		{"S2625","X-TEA Modeler - 배색설정 선택"},
		{"S2629","데이터모델の배색설정을 선택해 주세요. "},
		{"S2865","]へ점프"},
		{"S2864","["},
		{"S2870","점프"},
		{"S2871","플로우추가"},
		{"S2872","변경"},
		{"S2873","복사"},
		{"S2874","삭제"},
		{"S2875","숨기기"},
		{"S2876","Edit Instance"},
		{"S2877","전 관련선 표시"},
		{"S2954","신규플로우"},
		{"S3062"," ; 항상 대응한다"},
		{"S3063"," ; 참조키항목이 모두 Null이 아니면 대응한다"},
		{"S3221","(예제 값을 입력해 주세요)"},
		{"S3248","시스템 설명"},
		{"S3253","보수이력리스트"},
		{"S3268","서브시스템の설명"},
		{"S3305","이미지"},
		{"S3307","항목리스트"},
		{"S3319","- " },
		{"S3320","【 "},
		{"S3321"," 】"},
		{"S3326","["},
		{"S3327","]"},
		{"S3328","] / " },
		{"S3385","업무플로우"},
		{"S3391","직무별 담당업무"},
		{"S3401","서버모듈"},
		{"S3407","DB구성"},
		{"S3427","KEY구성"},
		{"S3433","기능구성"},
		{"S3442","(재귀)"},
		{"S3485","[注]"},
		{"S3528","신규업무플로우"},
		{"S3545","신규직무"},
		{"S3562","신규업무"},
		{"S3568","수시"},
		{"S3590","신규서브시스템"},
		{"S3606","신규테이블"},
		{"S3651","신규필드"},
		{"S3701","신규기능"},
		{"S3707","없음"},
		{"S3709","리턴 코드"},
		{"S3721","신규패널"},
		{"S3722","링크시에 업무정의상에 표시되는 설명문"},
		{"S3723","링크시에 업무정의상 표시되지 않는 설명문"},
		{"S3742","항목1"},
		{"S3750","신규스풀"},
		{"S3771","항목1"},
		{"S3777","신규페이지"},
		{"S3792","항목1"},
		{"S3802","이 담당자는 다른 업무를 담당하고 있기 때문에 삭제할 수 없습니다. "},
		{"S3811","]외, 합계"},
		{"S3810","이 업무는["},
		{"S3812","개의 업무플로우에 있어서 "},
		{"S3814","프로세스로서 놓여 있기 때문에, 삭제할 수 없습니다. "},
		{"S3820","이 서브시스템에는 (내부)테이블이 포함되어 있기 때문에, 삭제할 수 없습니다. "},
		{"S3824","이 서브시스템에는 다른 기능이 포함되어 있기 때문에, 삭제할 수 없습니다. "},
		{"S3830","이 테이블은 다른 기능에 이용되고 있기 때문에, 삭제할 수 없습니다. "},
		{"S3835","이 테이블은 테이블관련정의를 포함하고 있기 때문에, 삭제할 수 없습니다. "},
		{"S3844","]에 있어서 "},
		{"S3843","이 테이블은 ["},
		{"S3846","외부테이블로 등록되어 있기 때문에 , 삭제할 수 없습니다. "},
		{"S3848","]외, 합계"},
		{"S3847","이 테이블은 ["},
		{"S3849","개의 서브시스템에 있어서 "},
		{"S3851","외부테이블로서 등록되어 있기 때문에 삭제할 수 없습니다. "},
		{"S3858","이 항목은 이 테이블의 다른 키에 포함되어 있기 때문에 삭제할 수 없습니다. "},
		{"S3866","이 항목에 대한 처리내용이 블랭크가 아닌 기능이 존재하고 있기 때문에 삭제할 수 없습니다. "},
		{"S3878","일차 식별자는 필수이므로 삭제할 수 없습니다. "},
		{"S3884","이 키는 테이블관련정의를 포함하기 때문에 삭제할 수 없습니다. "},
		{"S3897","이 기능은 다른 업무에서 이용되고 있기 때문에 삭제할 수 없습니다. "},
		{"S3903","이 기능은 다른 기능에 의해서 이용되고 있기 때문에 삭제할 수 없습니다. "},
		{"S3911","이 패널은 다른 업무で이용되고 있기 때문에 삭제할 수 없습니다. "},
		{"S3922","이 스풀은 다른 업무で이용되고 있기 때문에 삭제할 수 없습니다. "},
		{"S3937","이 페이지은 다른 업무で이용되고 있기 때문에 삭제할 수 없습니다. "},
		{"S3951","(복사)"},
		{"S4556","시스템정의"},
		{"S4606","리스트"},
		{"S4623","직무리스트"},
		{"S4632"," - 업무리스트"},
		{"S4695","이 엑션은 서버와 통신하지 않습니다"},
		{"S4911","고유"},
		{"S4914","계승"},
		{"S4917","도출"},
		{"S4936","No"},
		{"S4937","OK"},
		{"S5007","일차 식별자(PK)"},
		{"S5011","외부키(FK)"},
		{"S5014","이차식별자(SK)"},
		{"S5015","Index(IX)" },
		{"S5032","관련종류"},
		{"S5033","다중도"},
		{"S5036","KEY"},
		{"S5037","존재조건"},
		{"S5050","부모자식관계"},
		{"S5051","1:N"},
		{"S5052","(지정불능)"},
		{"S5055","참조관계"},
		{"S5060","파생관계"},
		{"S5064","1:1 또는 0"},
		{"S5161","기능명"},
		{"S5162","인수"},
		{"S5163","기동이벤트"},
		{"S5219","라벨"},
		{"S5220","항목명"},
		{"S5221","항목종류"},
		{"S5226","GUI부품"},
		{"S5225","표시전용항목"},
		{"S5224","필수입력항목"},
		{"S5223","옵션입력항목"},
		{"S5269","설정된 값"},
		{"S5301","항목에 대한 조작"},
		{"S5425","이 기능은 이미 관련되어 있기 때문에 추가할 수 없습니다. "},
		{"S5586","테이블관련을 포함하기 때문에 키정의는 변경할 수 없습니다. "},
		{"S5595","이 항목은 이미 포함되어 있기 때문에 추가할 수 없습니다. "},
		{"S5600","경고:키정의에 동일한 데이터종류의 필드가 함께 있기 때문에 도구메뉴의 [CreateTable문 출력]의 "},
		{"S5602","실행시에 이 키에 기반된 부모자식관계에 있는 자식에서 부모에 대한 참조제약이 올바르게 설정되지 않을 가능성이 있습니다. "},
		{"S5604","자세한 것은 도움말의 키정의에 관한 설명을 참조해 주세요"},
		{"S5628","지정된 키의 조합에 기반한 관련정의가 이미 존재합니다. "},
		{"S5631","외부키(FK)의 조합에 대해서 테이블관련은 성립하지 않습니다. "},
		{"S5703","지정된 키의 조합에 대한 테이블관련은 성립하지 않습니다. 키에 포함된 데이터항목 수나 데이터종류를 조정해 주세요"},
		//{"S5713","이 입출력정의는 이미 관련되어 있기 때문에  추가할 수 없습니다. "},
		{"S5728","이 업무는 이미 배치되어 있기 때문에 추가할 수 없습니다. "},
		{"S5748","이 테이블은 이미 데이터모델상에 존재하기 때문에 추가할 수 없습니다. "},
		{"S5750","이 테이블은 이미 서브시스템에 관련되어 있기 때문에 추가할 수 없습니다. "},
		{"S5760","경고:서브시스템사이에 결합도를 억제하기 위해서 다른 서브시스템이 주관"},
		{"S5761","하는 테이블에 대한 C,U,D조작은 가능한 피해 주시기 바랍니다. 서브시스템"},
		{"S5762","구성을 변경하던가, 갱신용 관수를 사용하는 등의 방법을 고려하시기 바랍니다. "},
		{"S6450","변경있음"},
		{"SplashMessage0", "Launching X-TEA Modeler..." },
		{"SplashMessage1", "Parsing System Definitions..." },
		{ "XF000Name", "Script Launcher" },
		{ "XF100Name", "List Display" },
		{ "XF110Name", "List Update" },
		{ "XF200Name", "Flat Maintenance" },
		{ "XF290Name", "Flat Print" },
		{ "XF300Name", "Header-Detail Display" },
		{ "XF310Name", "Header-Detail Update" },
		{ "XF390Name", "Header-Detail Print" },
		{ "XF000Desc", "Function to execute specific script code" },
		{ "XF100Desc", "Function to list records in the primary table" },
		{ "XF110Desc", "Function to list and update records in the primary table" },
		{ "XF200Desc", "Function to show/insert/update/delete a specific record in the primary table" },
		{ "XF290Desc", "Function to print a specific record in the primary table" },
		{ "XF300Desc", "Function to show a specific record in the header table and multiple records in the detail table" },
		{ "XF310Desc", "Function to update a specific record in the header table and multiple records in the detail table" },
		{ "XF390Desc", "Function to print a specific record in the header table and multiple records in the detail table" },
		{"XLSFontDTL", "Times New Roman" },
		{"XLSFontHDR", "Arial" }};
	public Object[][] getContents() {
		return contents;
	}
}
